### ISSUE TITLE
disable sharpness totally

### ISSUE THREAD

**Issue by neoedmund** [fholger/openvr_fsr#100]
Suggest disable sharpness totally when `sharpness` is set to `0`.
Apply sharpness with 0 still alter the image.
I found it usually gets better result without sharpness. 
So please consider change code like
PostProcessor.cpp ( line:486 )
```
		if (Config::Instance().fsrEnabled && Config::Instance().sharpness != 0) {
			ApplySharpening(eEye, inputView);
			outputTexture = sharpenedTexture.Get();
		}
```
It also add performance when omit sharpness step.

**Comment by fholger** [comment]
To me, that sounds like a bad idea. The EASU upscaler alone creates a blurred image, and the whole FSR algorithm is specifically designed to work in conjunction with the sharpening pass to restore some of the lost detail. In other words, without the sharpening pass, it's not even FSR.

What games are you testing where you think you get a better image without the sharpening pass?

**Comment by neoedmund** [comment]
Blur image is not bad, that's why people use anti-aliasing like TAA ,FXAA. and sharpen is not always good, it add noise. 
You also can try https://github.com/GPUOpen-Effects/FidelityFX-CLI on images, the default method is EASU, and the result is always more clear.

**Comment by neoedmund** [comment]
Since this openvr_fsr not support vulkan nor dx12 currently, I cannot test on game like "no man's sky" or openvr samples hellovr.

**Comment by fholger** [comment]
> Blur image is not bad, that's why people use anti-aliasing like TAA ,FXAA. and sharpen is not always good, it add noise.
> You also can try https://github.com/GPUOpen-Effects/FidelityFX-CLI on images, the default method is EASU, and the result is always more clear.

But here you are talking about flat images. This is a VR mod, and the situation in VR is *very* different to simple images. Blur is a much more significant issue in VR. So I ask again: what VR game did you try where you felt that a sharpness level of 0 made the game too sharp?

**Comment by neoedmund** [comment]
I have no dx11 VR game now to test. Only dx12(hellovr) and vulkan(NMS) ones. So actually I only see the performance is good because of the smaller rendering dimension, but cannot check visual quality. 
All my conclusion is based on static image. I hope I can test on VR if FSR plugin is also supported on vulkan rendered VR.

**Comment by fholger** [comment]
Well, until such time I'm going to keep the algorithm as it is.
