### ISSUE TITLE
Euro truck simulator doesn't seem to work

### ISSUE THREAD

**Issue by ASHOT3359** [fholger/openvr_fsr#101]
Using Oculus Quest 2, -openvr in steam launch parameters. I have set the render scale to 0.50 in openvr_mod.cfg just so i can see if the mod working by making the screen blurry. It did not. Everything seems the same as it was before.

Here is openvr_mod.log
```
Initializing hooks...
Requested interface IVRSystem_021
Injecting GetRecommendedRenderTargetSize into IVRSystem_021
Requested interface FnTable:IVRSystem_021
Requested interface IVRCompositor_026
Injecting Submit into IVRCompositor_026
Requested interface FnTable:IVRCompositor_026
Creating post-processing resources
Input texture is in SRGB color space
Input texture can't be bound directly, need to copy
Creating copy texture of size 1936x1952
Creating upscaled texture of size 3872x3904
Creating sharpened texture of size 3872x3904
Injecting PSSetSamplers into D3D11DeviceContext
Creating replacement sampler for 0000018FF005BD20 with MIP LOD bias -1
Creating replacement sampler for 0000000000000000 with MIP LOD bias -1
Creating replacement sampler for 0000018FF095E2E0 with MIP LOD bias -1
Creating replacement sampler for 0000018FEF4FDDA0 with MIP LOD bias -1
Creating replacement sampler for 0000018FF1B3FB20 with MIP LOD bias -1
Creating replacement sampler for 0000018FEF0A8820 with MIP LOD bias -1
Creating replacement sampler for 0000018FEF0A98E0 with MIP LOD bias -1
Creating replacement sampler for 0000018FF1B3F220 with MIP LOD bias -1
Creating replacement sampler for 0000018FFB082F60 with MIP LOD bias -1
Creating replacement sampler for 0000018FF095D0E0 with MIP LOD bias -1
Creating replacement sampler for 0000018FF095ECE0 with MIP LOD bias -1
Creating replacement sampler for 0000018FFB085D60 with MIP LOD bias -1
Creating replacement sampler for 0000018FFB0894A0 with MIP LOD bias -1
Creating replacement sampler for 0000018FFB0884E0 with MIP LOD bias -1
Creating replacement sampler for 0000018FFD35E9A0 with MIP LOD bias -1
Creating replacement sampler for 000001909C5107A0 with MIP LOD bias -1
Creating replacement sampler for 000001909C66E3E0 with MIP LOD bias -1

```

It's doing...something?

**Comment by fholger** [comment]
It's working fine, but it is upscaling from a rendered resolution of 1936x1952 to a very high resolution of 3872x3904. Either you have configured a massive supersampling amount in either SteamVR or Oculus or the game itself, or the game is bypassing the mod's request to render at a lower resolution.

**Comment by ASHOT3359** [comment]
> It's working fine, but it is upscaling from a rendered resolution of 1936x1952 to a very high resolution of 3872x3904. Either you have configured a massive supersampling amount in either SteamVR or Oculus or the game itself, or the game is bypassing the mod's request to render at a lower

**Comment by ASHOT3359** [comment]
Well yes, I do have increased ss in a game config. Also in oculus i have 80% of the fov and increased ss. In steamvr i have 80% fov without ss.

I don't think the mod is launching then using oculus since it didn't create a log file.

Will try to turn all this off then im back home. Game config especially.

**Comment by ASHOT3359** [comment]
Question. Can i set render scale to more than 70, 100%? Will it work as an ss?

**Comment by fholger** [comment]
> I don't think the mod is launching then using oculus since it didn't create a log file.

It's not, but I'm not sure right now if SteamVR passes Oculus supersampling along.

> Question. Can i set render scale to more than 70, 100%? Will it work as an ss?

Yes, you can. But keep in mind that the FSR cost is proportional to the target upscaled resolution, so if you try to set high upsampling scales for FSR, it will probably just end up costing you quite a bit of performance for questionable image improvements.
