### ISSUE TITLE
Easy cheat service blocking iRacing to start

### ISSUE THREAD

**Issue by hendrik-bene-perdok** [fholger/openvr_fsr#102]
Hi,
Not sure if it was going to work but I tried it. I followed the instructions and this was the result. See the screenshots. 

![Screenshot 2021-09-21 001555](https://user-images.githubusercontent.com/28087812/134083326-9f18cf1b-3181-4706-9dcf-0501b9fb5a8a.png)

![Screenshot 2021-09-21 001617](https://user-images.githubusercontent.com/28087812/134083328-12057a02-18d9-48ad-95c9-76401788c0d4.png)

**Comment by cikeZ00** [comment]
Don't expect it to work on any game that has an anticheat that checks file integrity.

Since you're basically modifying "game files".

(EasyAntiCheat in this case)
