### ISSUE TITLE
Hard Bullet VR

### ISSUE THREAD

**Issue by DasaniSamurai** [fholger/openvr_fsr#103]
There's a weird issue with FSR + HBVR that screws with the stereoscopic correction, like it moves the two rendered images closer(or further?) horizontally than where they should be

**Comment by fholger** [comment]
You could retry with the latest v1.3 as it fixes a potential problem in newer Unity builds. I'm afraid I don't own the game and can't investigate it myself.

**Comment by Crimson-foxGITHUB** [comment]
@fholger Whatever fix you did in 1.3, it worked, you can close the issue now.
