### ISSUE TITLE
Could not switch to vr mode in fs2000

### ISSUE THREAD

**Issue by PhatJ420** [fholger/openvr_fsr#104]
It was not a difficult fix but it was not in the readme.  I am running Win11 Pro x64.  The instructions you provided have to be done twice.  One in x86 and one in x64.

**Comment by fholger** [comment]
I'm not sure what you mean. What is FS2000? Also, the DLL provided in the package is only for x64, if you copied it to an x86 folder, that is almost certainly not correct.
