### ISSUE TITLE
Can this work with War Thunder?

### ISSUE THREAD

**Issue by JBB888** [fholger/openvr_fsr#106]
Didn't work when I tried it, I guessed because its an online game but could it work at all?

**Comment by fholger** [comment]
How exactly did it not work?

**Comment by JBB888** [comment]
put the 2 files in to /x64 with the game exe enabled debug mode in config and when game is running doesnt show the red circle

**Comment by fholger** [comment]
But was there an openvr_api.dll in that folder to begin with? If not, it's not the right directory.

**Comment by JBB888** [comment]
yes there was, i renamed it and copied yours in

**Comment by JBB888** [comment]
the log is empty too :(

**Comment by fholger** [comment]
Check if there's a different place where an openvr_api.dll exists. Potentially some plugin folder or similar. Sometimes, there's more than one copy, and you need to replace the right one.

**Comment by JBB888** [comment]
apenvr.api.dll has 2 copies in /warthunder/win32 and /warthunder/win64 I tried both still doesnt work. However I think I know why now openxr_loader.dll is in both folders too which reminded me a few months ago War Thunder changed the type of VR or something and it broke VR for a lot of people. So I guess its because War Thunder is using OpenXR instead now? Since the change all my OVR_Advanced_Settings settings no longer work too, I cant move the playspace around anymore get the error 'unknown Tracking Universe'.

**Comment by fholger** [comment]
Yes, I'm afraid if the game is using OpenXR, then the mod will not work.

**Comment by JBB888** [comment]
Ok, good to know, now I know why OVR Advanced Settings stopped working too.
