### ISSUE TITLE
One corner of one eye not applying shadows (Quest 1 Virtual Desktop SkyrimVR)

### ISSUE THREAD

**Issue by Aarondorn2** [fholger/openvr_fsr#107]
I have a rather odd one.  It may be related to an interaction with another mod/ENB but the issue goes away when I turn off FSR (revert to original openvr_api.dll) so I figured I'd start here first.

While playing, the top left corner (seems to be a perfect quarter of the screen) of one eye does not seem to apply shadows correctly.  It's much more noticeable on some surfaces than others and seems to be a specific type of shadow (possibly those generated by ambient occlusion or something similar).  This effect isn't applied to the other eye, or to the desktop mirror.  I've tried setting the `radius` to 2 and `applyMIPBias` to false but the problem persists.  It goes away when I revert the dll OR when I have a typo in the .cfg file (I accidentally left out a `,`).

Any advice on what to look at or try next would be great - this is immersion-breaking, but your mod is too good for me to turn off entirely. :)

**Comment by fholger** [comment]
Unfortunately, I don't really have any tangible suggestions. The mod works fine with unmodded Skyrim, so your speculation that it might be a conflict with another mod is likely. I'd start by disabling ENB, then removing any SKSE plugin dlls; those would be the most likely candidates.
