### ISSUE TITLE
asgard's wrath strange things

### ISSUE THREAD

**Issue by Ronln** [fholger/openvr_fsr#108]
10700
6600XT 21.10.1
21h1

quest 2 app rendering 1.5 (5k)
0.77 - 0.99 ~45 fps
67 ~30 fps
50 ~20 FPS

installed to 
Asgard's Wrath/WrathGame/Binaries/Win64/openvr_api.dll
Asgard's Wrath/WrathGame/Binaries/Win64/x64/openvr_api.dll

**Comment by fholger** [comment]
Asgard's Wrath is an Oculus game, the mod can't work with that game directly. You'd need to run it through Revive and replace the Revive openvr DLLs instead. However, if you have a Quest, running it natively with Oculus is probably better for performance than going through Revive even with the mod.

**Comment by Ronln** [comment]
I see, Thank you.
