### ISSUE TITLE
IPD way out of alignment in Unity Project

### ISSUE THREAD

**Issue by s13n1** [fholger/openvr_fsr#110]
Forgive me if my methods for testing this are completely wrong, but after building my Unity project i replaced the files in the plugin directory, everything loaded fine and changes made to the render scale look to be working, but the image is not aligned as if the IPD is very wrong.

I did try setting the radius to 2.0, but it didn't help.

I'm on a HP Reverb G1, log attached.

[openvr_mod.log](https://github.com/fholger/openvr_fsr/files/7361269/openvr_mod.log)

Looking at the log you can see the projection center is off. I looked at some other peoples logs and their values are almost identical for each eye.

Projection center for eye 0: 0.540255, 0.496382
Projection center for eye 1: 0.459177, 0.497269

My game isn't running dynamic resolution, i tried building a SteamVR demo scene and it didn't work either.

Update:

Okay i figured it out!
Using multipass rendering instead of singlepass instanced fixed it. The difference is amazing. Now i need to test different builds with and without AA, various rendr scales etc. And i need some sleep!

**Comment by fholger** [comment]
The projection centers look fine. They depend on the headset and are generally expected to be off-center, although by how much varies.

Unfortunately, I can't really tell from the logs why the single pass mode doesn't work. The most likely culprit for misaligned images is that the same image ends up being used for both eyes, killing the stereo separation and just looking wrong. This could be a bug in the mod, but it would require some (graphical) debugging to figure out what is happening.

**Comment by fholger** [comment]
It appears that newer Unity versions submit array textures to OpenVR, which the mod did not handle correctly (it is an undocumented feature). You might want to try again with v1.3.

**Comment by s13n1** [comment]
Nice work! 

It does indeed fix the issue for me, but I'm using a grass asset that's not setup to run single pass, so hopefully the author can update the shaders, otherwise ill have to stick with multipass as the grass is too nice to give up.

Just out of curiosity, why is the modified openvr_api.dll so much smaller than the one Unity spits out? The Unity file is about 800kb.

**Comment by fholger** [comment]
Thanks for the confirmation.

As for the size: the OpenVR Github repo, from my understanding, is only a stripped out mirror from the actual internal Valve repositories. Valve provides prebuilt DLLs that contain some extra stuff not in the publically available repo. So if you build it yourself, the DLLs end up smaller in size. I'm not sure what exactly the extra pieces are, but in practice it doesn't really seem to matter.
