### ISSUE TITLE
Mod does not seem to work with Elite Dangerous Horizons or Odyssey

### ISSUE THREAD

**Issue by Cailess** [fholger/openvr_fsr#112]
Tested this with Elite Dangerous, and was not seeing any performance differences to I turned on debug mode and sure enough it wasn't working.

**Comment by jacklul** [comment]
Elite Dangerous Odyssey has FSR build-in, also if you're on Oculus headset the game will always prefer Oculus API over SteamVR.
No idea about DX levels

**Comment by fholger** [comment]
Need more info here. How exactly did you install the mod, what headset are you using? Is it working in other games?

**Comment by Cailess** [comment]
Nevermind me, was at the end of my rope and apparently just needed to take 24 hours. I have it running perfectly now and it's helping my aging 6850K and GTX 1080 run odyssey at somewhat reasonable quality.
