### ISSUE TITLE
Blade and Sorcery inverted eyes?

### ISSUE THREAD

**Issue by ASchneiderBR** [fholger/openvr_fsr#113]
Hello guys! After updating to U10, when I load the game, it starts with my eyes switched up. When I remove the DLL, game starts correctly. Does it happens to you too? Thanks!

**Comment by Codex-18** [comment]
Yeah happened to me too

**Comment by agrastiOs** [comment]
Same. The world scale is also too large.

**Comment by TheDaxit** [comment]
Same thing happening.

**Comment by ThatsFluke** [comment]
same here. the world seems too large too, like i have a MASSIVE fov.

**Comment by fholger** [comment]
Today I learned you can submit array textures in OpenVR, and it will implicitly select one slice of the array depending on the eye. As far as I can tell, this is completely undocumented (for D3D11), how fun.

Should be fixed in v1.3.
