### ISSUE TITLE
Pavlov VR, Rec Room, and The Walking Dead: Saints & Sinners

### ISSUE THREAD

**Issue by Crimson-foxGITHUB** [fholger/openvr_fsr#117]
Pavlov VR uses Unreal Engine 4, and Rec Room uses Unity. However, both games fail to start up using the OpenVR DLL file since they use EasyAntiCheat: an "unknown version" error. Maybe you need a different approach to injecting FSR for those games.

The Walking Dead: Saints & Sinners isn't compatible if you are using an Oculus headset since Skydance Interactive configured the input system specifically for Vive wands. (detects by HMD instead of by controller type) There's no known fix, but as far as I'm aware, it's the same issue that makes the game incompatible with Quest 2 Virtual Desktop and the HP Reverb G2.

**Comment by WizzDude** [comment]
Pavlov still opens fine for me, before and after the EasyAntiCheat update. Rec Room I don't plan on trying and I don't own walking dead

**Comment by jacklul** [comment]
Walking Dead S&S worked fine for me back in the day with Quest 1, had to use custom controller layout in SteamVR though.
You might've replaced wrong dll if you have controller problems

**Comment by sycspysycspy** [comment]
> Pavlov VR uses Unreal Engine 4, and Rec Room uses Unity. However, both games fail to start up using the OpenVR DLL file since they use EasyAntiCheat: an "unknown version" error. Maybe you need a different approach to injecting FSR for those games.
> 
> The Walking Dead: Saints & Sinners isn't compatible if you are using an Oculus headset since Skydance Interactive configured the input system specifically for Vive wands. (detects by HMD instead of by controller type) There's no known fix, but as far as I'm aware, it's the same issue that makes the game incompatible with Quest 2 Virtual Desktop and the HP Reverb G2.

If EAC give you unknown version message try different OpenFSR versions. For example I used 1.2 on onward without any issue, after I changed to 1.3 EAC reported this error.
