### ISSUE TITLE
Latest version of openvr_fsr not working on vrchat

### ISSUE THREAD

**Issue by NoobiBoobi** [fholger/openvr_fsr#121]
With the latest version of the openvr_fsr the image just looks low res. Not entirely sure but seems it's down scaling but not up scaling the image.

**Comment by fholger** [comment]
That sounds weird. Can you confirm that the previous version still works as expected?

**Comment by NoobiBoobi** [comment]
After trying a older version and trying it on boneworks ( Didn't own until very recently) It just doesn't seem to work on my system. Only thing I can think of is updating my drivers recently either way its not working so i'm gonna try and figure that out
