### ISSUE TITLE
openvr_fsr not upscaling the image. 

### ISSUE THREAD

**Issue by NoobiBoobi** [fholger/openvr_fsr#122]
Tried with latest release version fsr_v2/0 and with version fsr_v1.0. Using a Rx 570.
Using render scale 0.50 and .77 showed the game looked better at 77 but still wasn't using native res and looked pretty bad.
Tried both Vrchat and Boneworks. Vrchat used to work fine and Boneworks I didn't have access to. 
Gonna try using a older driver later as that's the only thing I'm able to think of.

**Comment by fholger** [comment]
The log file specifically tells you what resolutions are being used. Please post that file here. Also, please double-check what target resolution you actually have configured in SteamVR for the specific game.

**Comment by NoobiBoobi** [comment]
Target resolution is 100% 1392 x 1424
[openvr_mod.log](https://github.com/fholger/openvr_fsr/files/7609927/openvr_mod.log)
Heres the log after opening boneworks with renderScale set to 0.50
Reverting to a older driver did not work

**Comment by fholger** [comment]
That resolution is *way* too low! Combined with a renderScale of 0.5, it means that the game is rendering at a resolution of only 696x712 pixels. There's nothing any simple upscaler can do to make that look any sort of decent. You'll have to use higher resolutions, also higher renderScale, probably.

**Comment by NoobiBoobi** [comment]
Huh really? It's worked perfectly fine up until recently and the performance was better. weird
