### ISSUE TITLE
please add Nvidia dlss its open source now

### ISSUE THREAD

**Issue by Manni1000** [fholger/openvr_fsr#123]
Hi it would be cool if u could add Nvidia dlss to the mod it is open source now and workes on and amd Nvidia now.

**Comment by OliverMilas** [comment]
ED should consider it too

**Comment by fholger** [comment]
You must have mixed up some information somewhere. DLSS is not open source nor does it work on anything other than RTX cards. The SDK is now freely available, but that doesn't really help. What Nvidia did open source and does run on AMD cards is its NIS algorithm, and that's already integrated into this mod.

Even if DLSS were actually open source, it is impossible to integrate it into this mod. Unlike FSR and NIS, DLSS is not just a post-process image scaler. It requires engine-level integration and must therefore be supported on the engine. It cannot be injected generically by a mod. That could only work on a game by game basis and only if the game's engine fulfilled the prerequisites for it.
