### ISSUE TITLE
seems to be completely unusable in spite of every possible cfg combination

### ISSUE THREAD

**Issue by nippanippa** [fholger/openvr_fsr#129]
I'm using a valve index headset with an nvidia gforce gtx 1080ti and an amd ryzen 7, I'm attempting to run the dll in vrchat.
The view appears to be upside down and zoomed in in both eyes, rendering it unusable. For some reason, the game hud is not upside-down and is rendering somewhat correctly, but is still zoomed in. I've tried every possible suggested cfg change and it had the same effect. I don't think fsr works with the valve index. The valve index has a larger fov than most headsets, this might be part of the issue but I'm not sure.

**Comment by fholger** [comment]
I'm developing on the Index, so I can guarantee you the Index is absolutely not the issue. However, I'm not using VRChat, so unfortunately I can't assist with that particular title. I do know people have used the mod with VRChat successfully in the past, so perhaps someone can assist you here.

You could try the mod with other games to see if you can get it to work at all. Alternatively, try an older version of the mod; it's always possible something broke.

**Comment by nippanippa** [comment]
aight, so unfortunately
2.0 - same issue
1.3 - same issue
1.2 - same issue
1.1 - same issue
1.0 - same issue
RC2 - same issue
RC1 - same issue
alpha 1.2 - same issue
alpha 1.1 - same issue
1.0 - same issue

it seems to run fine with Universe Sandbox and Vintage VR

I'll ask around youtube and discord, if I find someone with a solution I'll update this thread, but if someone who's gotten this running in vrchat could help me out with a reply here, I'd appreciate it.

**Comment by nippanippa** [comment]
okay it works, I was putting it in the wrong directory. For vrchat, it doesn't go in the same directory as the exe, it goes in VRChat\VRChat_Data\Plugins\x86_64 make sure to back up the original openvr_api.dll
