### ISSUE TITLE
NIS for OpenXR

### ISSUE THREAD

**Issue by ASchneiderBR** [fholger/openvr_fsr#130]
Hello @fholger, how are you today?

Sorry to bother you, but I would like to bring to your attention this project, in case you have missed: https://github.com/mbucchia/XR_APILAYER_NOVENDOR_nis_scaler

It seems that he was able to use NIS and OpenXR :)

This is amazing news, specially for Flight Simulator 2020 users.

Thanks!

**Comment by fholger** [comment]
I already linked it in the existing OpenXR issue #99.

**Comment by ASchneiderBR** [comment]
Got it! Thanks, have a great day :)
