### ISSUE TITLE
F2 key still activates with hotkeys  set to false

### ISSUE THREAD

**Issue by stuartaston** [fholger/openvr_fsr#131]
F2 Key is still being read by the driver even when:

`    "hotkeys": {
      // If enabled, you can change certain settings of the mod on the fly by
      // pressing certain hotkeys. Good to see the visual difference. But you
      // may want to turn off hotkeys during regular play to prevent them from
      // interfering with game hotkeys.
      "enabled": false,`

**Comment by fholger** [comment]
Thanks; I accidentally forgot to check for the config option if hotkeys are enabled. I uploaded a hotfix.

**Comment by speed-of-heat** [comment]
confirmed this is working thanks!
