### ISSUE TITLE
Suggestion: Add ability to specify left or right ctrl, alt, and shift modifiers for hotkeys, per hotkey if possible

### ISSUE THREAD

**Issue by tanrr** [fholger/openvr_fsr#134]
Would help avoid conflicts with keybinds if openvr_fsr hotkeys would allow specifying that the modifiers required are left or right, instead of the generic modifier.  That is, allow LCTRL, RCTRL, LALT, RALT, LSHIFT, and RSHIFT.

Additionally, allowing modifiers to be specified per hotkey, and allowing any combination of modifiers, would allow users to avoid most conflicts.

For example: 
Toggle FSR/NIS: LSHIFT+RSHIFT+F1 
Toggle Debug: LALT+RALT+LSHIFT+F2

**Comment by fholger** [comment]
I'm currently working on merging my existing openvr mods (FSR, fixed foveated) into a new project called VRPerfkit. As such, it is unlikely I will add any major features to this project. But feel free to check out the new one, it already supports what you are asking: https://github.com/fholger/vrperfkit
