### ISSUE TITLE
Updating config without restart

### ISSUE THREAD

**Issue by ethanporcaro** [fholger/openvr_fsr#136]
Could the config be updated without a restart? Considering FSR is realtime, could the parameters but updated too? Maybe not updating realtime, as to not slow down the algorithm, but every 5 seconds or so? Anyway, thanks so much for the project.

 By the way, it works with Squadrons really well, but sadly EAC makes the process difficult and I shouldn't really say how if got it to work (:

**Comment by fholger** [comment]
If you want to play around with the settings while in-game, that's what the hotkeys in the latest release are for. You can use them to modify the parameters and test their effect. You do have to manually update the config afterwards, though.
I'm not planning to add hot reload for the config file, as that would add some complexity to the setup.

**Comment by dogjutsu** [comment]
Could there be a hot key to dump what the hot-key modified settings are to a .log or something?   Possible I'm missing something, but playing with the hot keys doesn't help a lot because when I find something that works, hard to know what to then put into the config file.

**Comment by fholger** [comment]
The log file should show the changes in the values.

Either way, you are probably better off putting that feature request over at the successor project, (https://github.com/fholger/vrperfkit), as it's unlikely I will be doing any additional work on this mod.

**Comment by ethanporcaro** [comment]
Ok thanks. Didn't see them. Thanks for the fast response.
