### ISSUE TITLE
Blade & Sorcery, Hard Bullet, After The Fall Not Looking Right

### ISSUE THREAD

**Issue by FreelanceSeven** [fholger/openvr_fsr#137]
So, this worked really well with most of the games I played, so I tested it out on some other ones. The three games I listed, B&S, HB, and ATF, look like a flat screen was wrapped around me instead of actually making me feel like I'm in the world. Makes everything feel like it's much closer to my face, it's kinda hard to explain. I was wondering if there was some way to fix that, perhaps some setting I could change? Thank you for your time.

**Comment by StickJump** [comment]
Agree. You mean the 3D effect lost. Looks like game is using just 1 image and doubling it on both eyes, instead of making 2 images for 3D effect.

**Comment by FreelanceSeven** [comment]
Nailed it! Some other unity games, like Beat Saber, don't have this issue, so I wonder what's causing it.

**Comment by fholger** [comment]
Are you sure you are on the latest release? B&S, specifically, was fixed in 1.3 and was working fine for me when I last tested it. After The Fall, too.

**Comment by StickJump** [comment]
> 

Oh shit, you're right! I was using version 1.0! Will try in with latest release. Guess OP using old one as well.

**Comment by FreelanceSeven** [comment]
Oh yeah, the one I'm using is 1.0. I downloaded it recently, I'm wondering how I didn't find the 1.3 version.
