### ISSUE TITLE
Cannot install VrPerfKit from UI

### ISSUE THREAD

**Issue by ASchneiderBR** [fholger/openvr_fsr#138]
Hello!

Sorry to bother you, I've searched here for an answer and could not find it.

I'm unable to install VrPerfKit mod from the UI, this option is greyed out, not sure why:

![image](https://user-images.githubusercontent.com/25224882/151372882-1f0ddfa5-966b-482c-963f-b380ae537f7e.png)

Any ideas what could be causing this?

Thanks!

**Comment by fholger** [comment]
I assume you wanted to post this here: https://github.com/tappi287/openvr_fsr_app
I am not responsible for that app and can't help you, sorry.

**Comment by ASchneiderBR** [comment]
Oh wow, I'm so sorry about this, I was at the wrong tab :) Have a great day!
