### ISSUE TITLE
DCS error 108

### ISSUE THREAD

**Issue by davepastry** [fholger/openvr_fsr#14]
testing this in DCS where VR performance help is badly needed. program runs but per the log I'm getting error 108 in each eye when MSAA is enabled

**Comment by kinemitor** [comment]
FSR uses TAA as far as I know, mixing with any other antialiasing is probably not good?

**Comment by fholger** [comment]
No, FSR is not an anti-aliasing solution and in fact relies on the game having already done AA.

But as for the question: does the error repeat consistently, or is it just reported once or twice? If the game works, then it's probably completely harmless and can be ignored. In fact, it probably isn't even caused by the mod, the mod just catches and reports the error.

**Comment by evanswillo** [comment]
Process appears to work fine in DCS, excellent work thankyou.
Looking forward to future enhancements .
HP Reverb G1 6900XT

**Comment by davepastry** [comment]
comes up every time in the log if I have MSAA enabled

**Comment by fholger** [comment]
Yes, but does the log get spammed with it, or is it just a couple of lines? And is anything not working for you, i.e. is there an actual issue, or just the log?

**Comment by evanswillo** [comment]
Hi quick question how are you exiting DCS if I QUIT to Desktop from mission end I can see a statement in the log
Error when submitting for eye 0: 108
Error when submitting for eye 1: 108
Shutting down hooks...

If I quit the mission and go back to the main menu before exiting DCS log is OK
Initializing hooks...
Requested interface IVRSystem_019
Injecting GetRecommendedRenderTargetSize into IVRSystem_019
Requested interface IVRCompositor_022
Injecting Submit into IVRCompositor_022
Requested interface IVRExtendedDisplay_001
Creating post-processing resources
Input texture is in SRGB color space
Creating upscaled texture of size 2197x2155
Creating sharpened texture of size 2197x2155
Creating shader resource view for input texture 0000026900B4FDF8
Texture has size 1692x1660
Mapping format 1c
Creating shader resource view for input texture 000002696E813978
Texture has size 1692x1660
Mapping format 1c
Shutting down hooks...

Currently I have MSAAx2

**Comment by davepastry** [comment]
> Yes, but does the log get spammed with it, or is it just a couple of lines? And is anything not working for you, i.e. is there an actual issue, or just the log?

just comes up once, I'm not sure if its an issue for me, it seemed to be working but I seemed to be experiencing more image degradation at longer distances than other people? very subjective but I did seem to get the results I'm reading that other people were getting.

**Comment by fholger** [comment]
If it comes up just once, then it is most likely not an issue and probably not even caused by the mod.
