### ISSUE TITLE
Not working with vrchat

### ISSUE THREAD

**Issue by Invaliduser81** [fholger/openvr_fsr#148]
![Screenshot 2022-05-17 174723](https://user-images.githubusercontent.com/95740910/168915568-abe86ecf-ad4e-4229-9519-4171839e55b6.png)
When I install this on vrchat it doesn't work, form what I can see it only stops working when I edit the render scale.

**Comment by Crimson-foxGITHUB** [comment]
did you try the latest patch?

**Comment by Invaliduser81** [comment]
> 

Considering the fact the last release was lest year, I'd think so yes.

**Comment by Crimson-foxGITHUB** [comment]
oh wait you're using modded client LOL

VRChat's client was updated, it broke like all your mods lmfao.

**Comment by Invaliduser81** [comment]
how fun :D thanks for the response
