### ISSUE TITLE
FidelityFX FSR2 v2.1.0

### ISSUE THREAD

**Issue by ASchneiderBR** [fholger/openvr_fsr#155]
Hello @fholger! Sorry for bothering you but I just wanted to let you know that FSR 2.1 is now available :)

https://github.com/GPUOpen-Effects/FidelityFX-FSR2/releases/tag/v2.1.0

https://gpuopen.com/meet-fidelityfx-super-resolution-2-1/

Not sure if this can be used with your project...

Thanks!

**Comment by fholger** [comment]
Thanks. Unfortunately, FSR 2 is something completely different from FSR 1 and cannot be integrated generically in the same manner. See also https://github.com/fholger/openvr_fsr/issues/145

**Comment by ASchneiderBR** [comment]
Got it! Sorry about that, I forgot about it... Thanks!
