### ISSUE TITLE
H3VR Banding

### ISSUE THREAD

**Issue by yushirogowa7201** [fholger/openvr_fsr#16]
OpenVR_FSR does work with Hot Dogs, Horseshoes, and Hand Grenades, however I noticed there is a slight ray banding effect around objects, especially prevalent in the Friendly 45 Firing Range.

**Comment by EmersonBiggons** [comment]
I have a problem getting it to run for H3VR and others. Don't know why, it just says error when submitting for eye #
[openvr_mod.log](https://github.com/fholger/openvr_fsr/files/6834559/openvr_mod.log)

**Comment by fholger** [comment]
Try the RC2 release.

**Comment by fholger** [comment]
You can play around with the sharpness value and try disabling `applyMIPBias`. Aside from that, I'm afraid there isn't really anything I can do about banding artifacts.
