### ISSUE TITLE
Gaming version of Monitor?

### ISSUE THREAD

**Issue by jordanpucela** [fholger/openvr_fsr#17]
Could you create a version for monitor games other than VR?  I have a Gpd Win Max that would do very well in many games. Thanks

**Comment by fholger** [comment]
I'm afraid this mod isn't directly portable to flatscreen gaming, that would require a somewhat different approach. I'm sure someone will eventually do it, though, possibly the Reshade folks :)

Have to warn you, though. All testing so far strongly indicates that FSR is not a good fit for lower resolutions and weaker hardware. So I wouldn't hold my hopes up that it is actually beneficial for the Gpd Win devices. You are probably better of just using regular downsampling and possibly applying a sharpening filter (e.g. via Reshade).
