### ISSUE TITLE
[Question] should sharpening value be edited?

### ISSUE THREAD

**Issue by DFOXpro** [fholger/openvr_fsr#18]
In the openvr_mod.cfg there is a  `"sharpness":` value,
Should this value be modified like the  same value of renderScale or vise versa or just leave unedited?

**Comment by fholger** [comment]
You can definitely experiment with it. It determines how sharp the final image will appear. Generally, the lower the `renderScale` parameter, the higher `sharpness` should probably be. But there is no clear guideline on what value to use, it'll also depend on the particular game.

**Comment by kinemitor** [comment]
but what value is AMD using for each quality lvl?

**Comment by fholger** [comment]
I have seen different values in different games. I don't know if there will be a general recommendation, but for now, you'll just have to experiment per game and find a value that looks good to you.

**Comment by fholger** [comment]
With the official source release now out, I can tell you that AMD has no specific recommendations for the quality levels. They do recommend one general value as a starting point (which would map to about 0.9 for the sharpness parameter in the new release), but also explicitly say to experiment from there.
