### ISSUE TITLE
Not working in Pimax 8KX HMD

### ISSUE THREAD

**Issue by Potefar** [fholger/openvr_fsr#19]
Is this mod HMD dependent in any way ? I tried this mod with SkyrimVR.. It works with Odyssey+ HMD, but not with my Pimax 8KX. In the log it repeats the same error message: "Error when submitting for eye 0/1 105" Game will launch, but not in the HMD.  

[openvr_mod.log](https://github.com/fholger/openvr_fsr/files/6833283/openvr_mod.log)

**Comment by fholger** [comment]
105 is unsupported texture format. I changed formats in the latest release, you can try an earlier one and see if that works.

**Comment by Potefar** [comment]
You were right. Using v1.2 and it indeed works. Thank you, much appreciated!

**Comment by Potefar** [comment]
Not the best game for FSR though, too much foliage and stuff, makes shimmering even worse. Better quality\performance by lowering the SS actually.. oh well :)

**Comment by hotmale420360** [comment]
not working in Fallout 4 VR and H3VR, same bug, Oculus Quest 2.
Old version works well

**Comment by fholger** [comment]
RC2 should fix this.
