### ISSUE TITLE
Only works with Pavlov of the modern steam games"

### ISSUE THREAD

**Issue by patientx** [fholger/openvr_fsr#2]
Other than Skyrim and Fallout 4 , all of the games I've tried PCars2 , Dİrt Rally, Half-life Alyx (which gives error if dll is changed) only Pavlov works with this, I can see it working ingame and also got the log on the dll directory. Is this normal at this moment ?

**Comment by fholger** [comment]
It definitely works with a number of games, I've successfully tested e.g. Boneworks, Vanishing Realms, Borderlands, TWD: Saints & Sinners and others.

But I can't guarantee compatibility with all SteamVR games, I'm afraid. I can only try to improve compatibility bit by bit.

**Comment by patientx** [comment]
Boneworks "works" all right :) Probably games you tested are working ones and ones I tested are not working. I don't know the other ones but halflife definetly checks file size etc for the dll and doesnt start unless you put the original one.

**Comment by fholger** [comment]
Yes, I am aware, and the same is true for Star Wars Squadrons. Nothing I can do about that in the sort term, I'm afraid.

**Comment by patientx** [comment]
Thanks anyway keep up the good work.

**Comment by patientx** [comment]
> It definitely works with a number of games, I've successfully tested e.g. Boneworks, Vanishing Realms, Borderlands, TWD: Saints & Sinners and others.
> 
> But I can't guarantee compatibility with all SteamVR games, I'm afraid. I can only try to improve compatibility bit by bit.

Doesn't activate on Borderlands. Is there a cmdline parameter or something that forces it to use openvr ?

**Comment by fholger** [comment]
No idea, sorry. For me it just works. Have you tried launching it from within SteamVR?

**Comment by FolkSong** [comment]
Patientx maybe you've already realized this but just to spell it out, it sounds like you're an Oculus user and some of the games you're testing launch in Oculus mode rather than SteamVR. This mod will only work for SteamVR.

Dirt Rally jumped out at me because it has no SteamVR support at all, only Oculus (the sequel Dirt Rally 2.0 does supports both).

**Comment by rcrichton** [comment]
If you are an Oculus user and opt to launch using SteamVR when prompted should this then work?

**Comment by patientx** [comment]
> Patientx maybe you've already realized this but just to spell it out, it sounds like you're an Oculus user and some of the games you're testing launch in Oculus mode rather than SteamVR. This mod will only work for SteamVR.
> 
> Dirt Rally jumped out at me because it has no SteamVR support at all, only Oculus (the sequel Dirt Rally 2.0 does supports both).



> If you are an Oculus user and opt to launch using SteamVR when prompted should this then work?

No, not an oculus user.

**Comment by fholger** [comment]
> If you are an Oculus user and opt to launch using SteamVR when prompted should this then work?

Yes, it should.

**Comment by jordanpucela** [comment]
Hi, I must be doing something wrong because the games start but I don't notice anything. Do you have to activate it somewhere in Steam VR? I have tried to leave the parameters as they come in the openvr_mod.cfg file and also changing the values, but then how do I activate them in the game? Thanks

**Comment by fholger** [comment]
If you replaced the openvr_api.dll, then they should be active. If they are, they should produce a log file (openvr_mod.log), so check for that. If there's no log file, something went wrong.

**Comment by jordanpucela** [comment]
> Si reemplazó openvr_api.dll, entonces deberían estar activos. Si es así, deberían producir un archivo de registro (openvr_mod.log), así que verifique eso. Si no hay un archivo de registro, algo salió mal.

if I replaced it and I got a log file, but the game was exactly the same fps as before putting the mod. And I don't see anywhere how I can choose one or the other of the 4 FSR modes. 
And if I put the files of the new version 1.1 the game does not start.

**Comment by fholger** [comment]
How are you measuring FPS? In VR games, the FPS is usually locked by the headset's refresh rate. You need to look at frame time, where you should see a decrease in the GPU frame time.

To change the FSR mode, you need to edit the config file openvr_mod.cfg and change the "renderScale" parameter accordingly. The comments in the file contain the values for the original AMD presets, but you can also choose any other value.

**Comment by jordanpucela** [comment]
> ¿Cómo mides FPS? En los juegos de realidad virtual, el FPS generalmente está bloqueado por la frecuencia de actualización de los auriculares. Debe observar el tiempo de fotograma, donde debería ver una disminución en el tiempo de fotograma de la GPU.
> 
> Para cambiar el modo FSR, necesita editar el archivo de configuración openvr_mod.cfg y cambiar el parámetro "renderScale" en consecuencia. Los comentarios del archivo contienen los valores de los ajustes preestablecidos de AMD originales, pero también puede elegir cualquier otro valor.

The fps and time I measure it with the FPSVR.
I just made it work with the new version 1.1 in DCS and it is perfect, thank you so much, now to continue testing because the car seems that it does not work in any of them.

**Comment by fholger** [comment]
For the record: PCars2 and HL: Alyx cannot currently be made to work. They will require a different method of injection. Dirt Rally (1) is not a SteamVR game. I'm closing this one for now.
