### ISSUE TITLE
Image very bright in DCS 2.7.3 Open Beta

### ISSUE THREAD

**Issue by fooksca** [fholger/openvr_fsr#20]
I've just updated to [RC1](https://github.com/fholger/openvr_fsr/releases/tag/fsr_rc1) and it appears to have affected the brightness/gamma in DCS 2.7.3 Open Beta. The image is now very bright. This seems to be the opposite of issue #10 sadly.

The image looks normal/as expected in the mirror. I faked up some images which I can attach if you want, but "looks too bright" really does cover it.

(Excellent work, btw. Thank you!)

**Comment by rhylos** [comment]
I was just about to report the same experience with rc1a (with the color space rollback) in Elite Dangerous. 

To high gamma/brightness + softnesslike effect present.

If @fHolger hardcoded something in with the rc1 build perhaps we can have a config option. 


Performance does seem to have improved a little bit as well. Not much but a little. Every bit helps to make this useful in VR 

:)

**Comment by speed-of-heat** [comment]
The same experience in DCS, the mirror is fine the in HMD image is overly bright, adjusting the in game gamma doesnt seem to have an effect. I rolled back to the alpha and everything is fine, as has been said already, great community work , and thank you!

**Comment by fholger** [comment]
I need the logs...

The mirror is irrelevant, it is not affected by this mod.

**Comment by speed-of-heat** [comment]
which log files do you need?

**Comment by fholger** [comment]
The openvr_mod.log.

**Comment by speed-of-heat** [comment]
here is the RC1 Log 
[openvr_mod.log](https://github.com/fholger/openvr_fsr/files/6834408/openvr_mod.log)
that was from running a very quick flight

**Comment by fholger** [comment]
Ok, now I'm confused. Judging from the logs, it should work just fine.
You could try this test build, but if that does not fix it, I have honestly no idea what else to do.

[openvr_fsr_test.zip](https://github.com/fholger/openvr_fsr/files/6834496/openvr_fsr_test.zip)

**Comment by speed-of-heat** [comment]
ok that seemed to work, no super saturated gamma in dcs what changed ?

**Comment by fholger** [comment]
I reverted a change to the internal texture formats that's apparently causing more problems than it solves. RC2 is out.

**Comment by speed-of-heat** [comment]
yep that works :) thanks
