### ISSUE TITLE
Error when submitting for eye (Pavlov and H3VR)

### ISSUE THREAD

**Issue by EmersonBiggons** [fholger/openvr_fsr#21]
[openvr_mod.log](https://github.com/fholger/openvr_fsr/files/6834562/openvr_mod.log)
No idea, Im now going to try a test build you gave someone else and see if that works. But the one I used before seemed to not work at all.

**Comment by ScruffyRules** [comment]
I also get this, I'm using a Rift S for VRChat (SteamVR Beta 1.19.2)
I tried Alpha 1.2 and it worked fine, It's just RC1

**Comment by EmersonBiggons** [comment]
thank u. I think it has to do with oculus headsets with the RC1 update. Im using a Quest 2 myself

**Comment by fholger** [comment]
Should be fixed with the RC2 I just released.

**Comment by ScruffyRules** [comment]
> Should be fixed with the RC2 I just released.

Can confirm, fixed and everything seems to be working normally.
