### ISSUE TITLE
ACC fixed might need to be reapplied?

### ISSUE THREAD

**Issue by Sporedd** [fholger/openvr_fsr#22]
ACC has some textures missing when running.

Mainly the text on the break markers, and some on the steering wheel.

Maybe the acc fixes need to ne reapplied?

**Comment by fholger** [comment]
No, the fixes are still there. You can try disabling "applyMIPBias" in the config file, that's the only potentially relevant change I can think of.

**Comment by Sporedd** [comment]
Im an idot, i forgot to copy the new config file. 

Thanks for all your work, is there a donate button somewhere? or should i open a new issue for that ;-)

**Comment by Sporedd** [comment]
Interesting, its working correctly at 0.77 scale but when i lower it to 0.67 its not working!

![image](https://user-images.githubusercontent.com/48203160/126037525-c3d2eb3f-69aa-4b39-9668-b960159ac15a.png)

**Comment by fholger** [comment]
For reference, a setting of 0.67 would correspond to 45% render resolution in SteamVR (if you start from 100%). Could you test if the game renders fine without the mod, but at 45% SteamVR resolution?

**Comment by Sporedd** [comment]
Your guess that it is the applyMIPBiasis was correct. I Truned that off and now its working below .77.

**Comment by fholger** [comment]
Thanks, I'll close this one then.

**Comment by Sporedd** [comment]
Jup, did you make a donate button yet?

**Comment by fholger** [comment]
Thanks, but that won't be necessary :)
