### ISSUE TITLE
Tracking Issue

### ISSUE THREAD

**Issue by Baobabbo** [fholger/openvr_fsr#24]
I tried using openvr_fsr on VRChat, looks like everything loads just fine. The weird thing is that when i'm in-game everything looks good, but my "view point" seems to have some kind of offset from the actual head position: when i look up, down, left, right my viewpoint pivots/rotates around a point in space that is outside my head/HMD. What's more, my controllers aren't tracked, at all(even the buttons and analog sticks don't work). 

I'm using an Oculus Rift S, I even tried changing the OpenXR runtime (SteamVR or Oculus version), just in case.

The log looks fine? 
[openvr_mod.log](https://github.com/fholger/openvr_fsr/files/6836385/openvr_mod.log)

UPDATE: I'm having the same issue on Boneworks and BeatSaber
[https://imgur.com/a/k3unjmm](url)

**Comment by ThatsFluke** [comment]
what other plugins may you have? whats your openvr config like?

**Comment by feilen** [comment]
I appear to be having the same issue. I originally had OpenVR AdvancedSettings and OVR Toolkit, but I tested with those disabled to no avail. VRChat doesn't appear to know where my hands are, and appears to have my position rotate around the world origin based on headset rotation.

[openvr_mod.log](https://github.com/fholger/openvr_fsr/files/6963798/openvr_mod.log)

[steamvr.vrsettings.txt](https://github.com/fholger/openvr_fsr/files/6963803/steamvr.vrsettings.txt)
[vrcompositor.txt](https://github.com/fholger/openvr_fsr/files/6963823/vrcompositor.txt)
[vrmonitor.txt](https://github.com/fholger/openvr_fsr/files/6963824/vrmonitor.txt)
[vrserver.txt](https://github.com/fholger/openvr_fsr/files/6963825/vrserver.txt)
[vrdashboard.txt](https://github.com/fholger/openvr_fsr/files/6963826/vrdashboard.txt)
[vrclient_VRChat.txt](https://github.com/fholger/openvr_fsr/files/6963827/vrclient_VRChat.txt)
[vrclient_vrcompositor.txt](https://github.com/fholger/openvr_fsr/files/6963828/vrclient_vrcompositor.txt)
[vrclient_vrmonitor.txt](https://github.com/fholger/openvr_fsr/files/6963829/vrclient_vrmonitor.txt)

- VRchat has the issue
- Steam Tours refuses to launch with it installed
- Rez Infinite seems to work fine

**Comment by feilen** [comment]
Worked it out! For VRChat, I'd put the copy of openvr_api.dll in the root of VRChat/ (next to VRChat.exe), when VRChat's openvr_api.dll is actually located in a plugins directory. Replacing it in the right place works! Just mentioning that in README.md would probably be sufficient.

**Comment by fholger** [comment]
Thanks for reporting your findings and the eventual fix. I've put a note in the troubleshooting section of the README. I'll assume this issue can now be closed. :)
