### ISSUE TITLE
Reshade + FSR + VRchat = works only left EYE

### ISSUE THREAD

**Issue by Rulez777** [fholger/openvr_fsr#25]
Good day. We have noticed Reshade compatibility issue. Reshade + FSR, the radius smoothing (all FSR) is working just on left eye 
Oculus rift S 

![image](https://user-images.githubusercontent.com/16141800/126144369-401ab20c-e32f-4ee2-ae7d-e608107386f7.png)

**Comment by fholger** [comment]
You could try setting the `radius` setting to 2, see if that fixes the issue.

**Comment by ni1chigo2115** [comment]
what your use reshade build?(i use skyirm mod sharper eye include build)

**Comment by fholger** [comment]
Judging from reports from other users, I'm going to assume that setting the `radius´ to 2 fixes this, for now. There is also the related issue #27 if you wish to submit further information.
