### ISSUE TITLE
DCS fog layer visual artifact

### ISSUE THREAD

**Issue by davepastry** [fholger/openvr_fsr#26]
weird grid layer seen here: https://imgur.com/a/qS3INp5 

log isn't throwing any unexpected errors that I can see, only seems to effect the fog layer in a band around me, looked normal further out

**Comment by fholger** [comment]
I'm not sure there is much to be done about this. This might just be one of those effects that might need to be rendered after FSR, which a non-native integration simply can't do.

Unless it's an issue with the color space. Does the log say anything about SRGB color space?

**Comment by davepastry** [comment]
this is my log after a play session that involved this error: Initializing hooks...
Requested interface IVRSystem_019
Injecting GetRecommendedRenderTargetSize into IVRSystem_019
Requested interface IVRCompositor_022
Injecting Submit into IVRCompositor_022
Requested interface IVRExtendedDisplay_001
Creating post-processing resources
Input texture is in SRGB color space
Creating upscaled texture of size 2696x2997
Creating sharpened texture of size 2696x2997
Injecting PSSetSamplers into D3D11DeviceContext
Creating replacement sampler for 0000000000000000 with MIP LOD bias -0.377014
Creating replacement sampler for 0000024BCAFE1220 with MIP LOD bias -0.377014
Creating replacement sampler for 0000024BCAFDFCA0 with MIP LOD bias -0.377014
Creating replacement sampler for 0000024BCAFDCC60 with MIP LOD bias -0.377014
Creating replacement sampler for 0000024BCAFDE520 with MIP LOD bias -0.377014
Creating replacement sampler for 0000024BCAFDFBA0 with MIP LOD bias -0.377014
Creating replacement sampler for 0000024BCAFDE620 with MIP LOD bias -0.377014
Creating replacement sampler for 0000024BCAFDD420 with MIP LOD bias -0.377014
Creating replacement sampler for 0000024BCAFDF820 with MIP LOD bias -0.377014
Creating replacement sampler for 0000024BCAFDD660 with MIP LOD bias -0.377014
Creating replacement sampler for 0000024BCAFDFA60 with MIP LOD bias -0.377014
Creating replacement sampler for 0000024BCAFDE860 with MIP LOD bias -0.377014
Creating shader resource view for input texture 0000024BB962CBB8
Texture has size 2076x2308 and format 28
Creating shader resource view for input texture 0000024BB962D378
Texture has size 2076x2308 and format 28
Creating replacement sampler for 0000024C15586820 with MIP LOD bias -0.377014
Creating replacement sampler for 0000024BCAFDCD60 with MIP LOD bias -0.377014
Creating replacement sampler for 0000024C305366A0 with MIP LOD bias -0.377014
Creating replacement sampler for 0000024C1557A360 with MIP LOD bias -0.377014
Creating replacement sampler for 0000024C1557A220 with MIP LOD bias -0.377014
Creating replacement sampler for 00000251EDD51E60 with MIP LOD bias -0.377014
Creating replacement sampler for 0000024BB83D7C20 with MIP LOD bias -0.377014
Creating replacement sampler for 00000251EDD543A0 with MIP LOD bias -0.377014
Creating replacement sampler for 0000024C1556F1A0 with MIP LOD bias -0.377014
Creating replacement sampler for 00000251EDD51320 with MIP LOD bias -0.377014
Shutting down hooks...

**Comment by fholger** [comment]
You can try playing around with lower sharpness values, or potentially also disabling the "applyMIPBias". Other than that, I don't think there's anything I can do about it.

**Comment by fholger** [comment]
Aside from the given suggestions, I think there is nothing else that can be done here.
