### ISSUE TITLE
FSR radius out of sweetspot on wide Pimax headsets.

### ISSUE THREAD

**Issue by RamesTheGeneric** [fholger/openvr_fsr#27]
On Pimax headsets the radius setting seems to be inverted, causing the use of bilinear upscaling in the sweetspot of the lens while fsr is applied outside of the specified radius. Disabling the radius (setting radius to 2) appears to function as intended however. This seems to be the case regardless of fovated rendering. I set the sharpening to 1, radius to 0.6, and renderScale to 0.77 to highlight the effect I'm talking about. 

![fsr pimax right eye anotated](https://user-images.githubusercontent.com/53163624/126257773-26e81469-9461-462a-a4c1-9d32aba5db40.png)
This is an anotated screenshot of the steamvr headset view of the right eye. 

![20210719232536_1_vr](https://user-images.githubusercontent.com/53163624/126257889-d5d5a042-9890-4693-8c2e-1feceb92d29d.jpg)
This is a screenshot taken by steamvr. 

Here's my log if it helps. 

[openvr_mod.log](https://github.com/fholger/openvr_fsr/files/6845415/openvr_mod.log)

**Comment by fholger** [comment]
Does this happen in all games, or specifically VRChat? There is already a bug report for VRChat that might be related (#25).

However, one general remark I have to make: the radius is always applied from the *center* of the image (or the image's portion for a particular eye). If the sweet spot is significantly off-center, as your images might suggest, then I'm afraid there's very little I can do. There isn't any obvious way to find the actual sweet spot of a particular headset.

**Comment by RamesTheGeneric** [comment]
I'll test some more games and fov settings today. I'll also turn off ffr just to make it easier to see what's going on.

**Comment by rhylos** [comment]
I’ll test as well but gotta say I do appreciate this feature as it does help to improve performance a bit.





On Tuesday, July 20, 2021, 10:23, Rames The Generic ***@***.***> wrote:




I'll test some more games and fov settings today. I'll also turn off ffr just to make it easier to see what's going on.

**Comment by RamesTheGeneric** [comment]
> 
> 
> Does this happen in all games, or specifically VRChat? There is already a bug report for VRChat that might be related (#25).
> 
> However, one general remark I have to make: the radius is always applied from the _center_ of the image (or the image's portion for a particular eye). If the sweet spot is significantly off-center, as your images might suggest, then I'm afraid there's very little I can do. There isn't any obvious way to find the actual sweet spot of a particular headset.


It seems to be apparent in other games but it looks like you're correct about the center of the image not being where the sweetspot is on wide fov headsets. Here's some screenshots with the wide fov screenshot first. 


VRChat:
Engine: Unity

![20210720_182647_129_vr](https://user-images.githubusercontent.com/53163624/126404893-ee08f600-6107-41a9-9d72-aa618ca4c8b0.png)
![20210720_183647_656_vr](https://user-images.githubusercontent.com/53163624/126404898-cb548463-6850-4384-b40f-62c82be0db65.png)

Pavlov:
Engine: Unreal

![20210720_182910_132_vrCompressed](https://user-images.githubusercontent.com/53163624/126405082-4b4eb10c-03f3-496b-89f2-0b9b889419d9.png)
![20210720_183920_946_vrsmallfovCompressed](https://user-images.githubusercontent.com/53163624/126405285-4e2c78c9-d8b6-4537-8985-8b2193d98a80.png)

Boneworks:
Engine: Unity

![20210720_183256_094_vrWideCompressed](https://user-images.githubusercontent.com/53163624/126405505-0afe8609-fcec-4ffa-b69d-eaf1cef2a939.png)
![20210720_184039_669_vrSmallCompressed](https://user-images.githubusercontent.com/53163624/126405509-811fe9b7-c8fc-47e0-8e38-fe9aa4a9d5f2.png)

I don't know how feasible it would be but maybe some way to specify an offset for the radius or a rectangle area for fsr to be applied. That's what my monkey brain could come up with :P

**Comment by RamesTheGeneric** [comment]
> 
> 
> Does this happen in all games, or specifically VRChat? There is already a bug report for VRChat that might be related (#25).
> 
> However, one general remark I have to make: the radius is always applied from the _center_ of the image (or the image's portion for a particular eye). If the sweet spot is significantly off-center, as your images might suggest, then I'm afraid there's very little I can do. There isn't any obvious way to find the actual sweet spot of a particular headset.

I've been messing around with the code and I've managed to get the fsr radius to start at the center of the display outward. I can adjust how much of the fov is processed by the upscaling just by using the radius setting. As of now it acts as a large circle, part of which covers the screen so there really isn't any way to adjust how much vertically gets upscaled. It however is now offering tangible performance increases when using the pimax on wide fov. Before this, upscaling the enitre display would cause worse performance than native. This is more suited to headsets on "wide" fov settings as normal and small fit the old center radius just fine. I'm going to see if I can add settings to the config file to toggle between this and the old center one. I'm also going to see if I can decouple the upscaling and sharpening radius for sharpening the whole image while only upscaling a small portion as rcas doesn't seem to have much impact on performance. I've never used github for development and don't know what to do but i'd like to contribute to this once I get these settings added. If there's a better way to contact you please let me know.

**Comment by BrziJoe** [comment]
@RamesTheGeneric I tried your branch openvr_fsr_v1.0.1_MOD.zip with Pimax. Well I tried it with small fov only, but something is wrong; If I choose foveated rendering with radius in center, then I have sharp circles in front of me, almost perfect (small miss-match). 
But if I choose it not in center ("false"), then I have sharper right side on booth of my eyes.
It suppose to be sharper on inner side of booth eyes, of course.

Maybe is different on wider fov, but I didn´t try this.

**Comment by RamesTheGeneric** [comment]
@fholger I'll take a look at this more closely tomorrow. Thanks for telling me about it. It's very ossible I overlooked it during testing. I'll try to identify what you're seeing and see if I can fix it.

**Comment by RamesTheGeneric** [comment]
> 
> 
> @RamesTheGeneric I tried your branch openvr_fsr_v1.0.1_MOD.zip with Pimax. Well I tried it with small fov only, but something is wrong; If I choose foveated rendering with radius in center, then I have sharp circles in front of me, almost perfect (small miss-match).
> But if I choose it not in center ("false"), then I have sharper right side on booth of my eyes.
> It suppose to be sharper on inner side of booth eyes, of course.
> 
> Maybe is different on wider fov, but I didn´t try this.

Yeah I see what you mean. I'm going to try to do it without touching the shader code since it seems to be all wonky.

**Comment by RamesTheGeneric** [comment]
> 
> 
> @RamesTheGeneric I tried your branch openvr_fsr_v1.0.1_MOD.zip with Pimax. Well I tried it with small fov only, but something is wrong; If I choose foveated rendering with radius in center, then I have sharp circles in front of me, almost perfect (small miss-match).
> But if I choose it not in center ("false"), then I have sharper right side on booth of my eyes.
> It suppose to be sharper on inner side of booth eyes, of course.
> 
> Maybe is different on wider fov, but I didn´t try this.

@BrziJoe Here's an updated version. In my testing with multiple FOVs it looks good but i'd like someone else to try it out before I submit another pull request. 
https://github.com/RamesTheGeneric/openvr_fsr/releases/tag/fsr_v1.0.2_MOD

**Comment by BrziJoe** [comment]
Well, first of all, I do not see scaled difference between "cheap bilinear and expenciever supersampling filter" at all (same as on all versions). Maybe my game (IL-2) does not work good with this scaling, but generally to me everything is blurry and same. I will install Follout 4 vr to check it later, but for now I do not see scaling radius.
Maybe you know how and where (which game) to look for this?

Next, I am using sharpening 1.0, and I see it well in IL-2. This time you made 2 sharpening circles per eye :) Please take a look on my sketch here: https://ibb.co/n13dv7m
I tried it in small fov only, no need to go further when there is an issue at beginning.

**Comment by RamesTheGeneric** [comment]
> 
> 
> Well, first of all, I do not see scaled difference between "cheap bilinear and expenciever supersampling filter" at all (same as on all versions). Maybe my game (IL-2) does not work good with this scaling, but generally to me everything is blurry and same. I will install Follout 4 vr to check it later, but for now I do not see scaling radius.
> Maybe you know how and where (which game) to look for this?
> 
> Next, I am using sharpening 1.0, and I see it well in IL-2. This time you made 2 sharpening circles per eye :) Please take a look on my sketch here: https://ibb.co/n13dv7m
> I tried it in small fov only, no need to go further when there is an issue at beginning.

I just tested all of your settings in vrchat and I can't seem to recreate what you're seeing. Can you send a copy of your log? It's possible that the game just doesn't play nice with it but if there's any info in there I can use that would be great. Something I did notice however is that I need to open my steamvr dashboard and then close it before I could see the sharpening but other than that it seems to have worked as expected. This may just be a vrchat thing as I know yesterday it kept doing some weird offset with the eyes that could only be fixed by me reinstalling the game. Copying that dll to pavlov showed it worked fine though. Let me know what happens with Fallout 4 VR. 


Sharpening = 1.0
radius = 0.2
center_display = -0.4
![20210804_161637_118_vr](https://user-images.githubusercontent.com/53163624/128250820-e4772ec1-2eb4-41b7-9066-31196e06cfea.png)


center_display = -0.5
![20210804_161820_497_vr](https://user-images.githubusercontent.com/53163624/128250831-e0f2498e-bbaf-4a82-8bcc-88dbe04458e2.png)


center_display = 0.2
![20210804_161947_660_vr](https://user-images.githubusercontent.com/53163624/128250852-349458c2-9849-4126-8592-2224ea0e2739.png)


center_display = 1.0
![20210804_162202_540_vr](https://user-images.githubusercontent.com/53163624/128250867-3681e08f-b116-4ffd-9408-23b75d1bfd99.png)


center_display = 0
![20210804_162323_009_vr](https://user-images.githubusercontent.com/53163624/128250877-18f4dbb0-babd-4e14-87c4-cfad5c4fcb20.png)


center_display = -0.2
![20210804_162435_914_vr](https://user-images.githubusercontent.com/53163624/128250882-91e8cb0d-68d9-4dc3-9bf4-b1567e768668.png)

**Comment by BrziJoe** [comment]
I have something, but that checking is exauhsting for eyes :) 

I tried in Follout4vr scaling and sharpening, and I saw it, but it is not visible in my screenshot. I will send you just a log, something is fishy in it.
With paralel projections on, I have in steamvr 100% ss 3164x3948 - it is manually on that values.
I set render_scale=0.77, and log shows upscaled 6327x3946???
That should not be.
(checked 2 times)

FALLOUT LOG:
Initializing hooks...
Requested interface IVRSystem_019
Injecting GetRecommendedRenderTargetSize into IVRSystem_019
Requested interface IVRCompositor_022
Injecting Submit into IVRCompositor_022
Creating post-processing resources
Input texture is in SRGB color space
textureContainsOnlyOneEye: 0
Creating upscaled texture of size 6327x3946
Creating sharpened texture of size 6327x3946
Injecting PSSetSamplers into D3D11DeviceContext
Creating replacement sampler for 0000000000000000 with MIP LOD bias -0.377008
Creating shader resource view for input texture 000002543FB696F8
Texture has size 4872x3039 and format 28
Error when submitting for eye 0: 101
Error when submitting for eye 1: 101
Creating replacement sampler for 00000254AD4C6620 with MIP LOD bias -0.377008
Requested interface IVRRenderModels_005
Creating replacement sampler for 00000254AD4C8EA0 with MIP LOD bias -0.377008
Creating replacement sampler for 00000254AD4C7A60 with MIP LOD bias -0.377008
...

For IL-2 I will send you a screenshot with center_display=-0,3 ( https://ibb.co/Wy3bsCV )and log.
(pp off, steamvr 100% is 3056x3160)

IL2 LOG:
Initializing hooks...
Requested interface IVRSystem_015
Injecting GetRecommendedRenderTargetSize into IVRSystem_015
Requested interface IVRCompositor_020
Injecting Submit into IVRCompositor_020
Requested interface IVRChaperone_003
Creating post-processing resources
Creating sharpened texture of size 3056x3160
Injecting PSSetSamplers into D3D11DeviceContext
Creating replacement sampler for 000001C4FEFF42A0 with MIP LOD bias -0
Creating replacement sampler for 0000000000000000 with MIP LOD bias -0
Creating shader resource view for input texture 000001C4DBFE5978
Texture has size 3056x3160 and format 28
Creating replacement sampler for 000001C49008B060 with MIP LOD bias -0
Creating replacement sampler for 000001C49008BCA0 with MIP LOD bias -0
Creating replacement sampler for 000001C49008AF20 with MIP LOD bias -0

**Comment by RamesTheGeneric** [comment]
> I have something, but that checking is exauhsting for eyes :) 
> 
> I tried in Follout4vr scaling and sharpening, and I saw it, but it is not visible in my screenshot. I will send you just a log, something is fishy in it.
> With paralel projections on, I have in steamvr 100% ss 3164x3948 - it is manually on that values.
> I set render_scale=0.77, and log shows upscaled 6327x3946???
> That should not be.
> (checked 2 times)
> 
> FALLOUT LOG:
> Initializing hooks...
> Requested interface IVRSystem_019
> Injecting GetRecommendedRenderTargetSize into IVRSystem_019
> Requested interface IVRCompositor_022
> Injecting Submit into IVRCompositor_022
> Creating post-processing resources
> Input texture is in SRGB color space
> textureContainsOnlyOneEye: 0
> Creating upscaled texture of size 6327x3946
> Creating sharpened texture of size 6327x3946
> Injecting PSSetSamplers into D3D11DeviceContext
> Creating replacement sampler for 0000000000000000 with MIP LOD bias -0.377008
> Creating shader resource view for input texture 000002543FB696F8
> Texture has size 4872x3039 and format 28
> Error when submitting for eye 0: 101
> Error when submitting for eye 1: 101
> Creating replacement sampler for 00000254AD4C6620 with MIP LOD bias -0.377008
> Requested interface IVRRenderModels_005
> Creating replacement sampler for 00000254AD4C8EA0 with MIP LOD bias -0.377008
> Creating replacement sampler for 00000254AD4C7A60 with MIP LOD bias -0.377008
> ...
> 
> For IL-2 I will send you a screenshot with center_display=-0,3 ( https://ibb.co/Wy3bsCV )and log.
> (pp off, steamvr 100% is 3056x3160)
> 
> IL2 LOG:
> Initializing hooks...
> Requested interface IVRSystem_015
> Injecting GetRecommendedRenderTargetSize into IVRSystem_015
> Requested interface IVRCompositor_020
> Injecting Submit into IVRCompositor_020
> Requested interface IVRChaperone_003
> Creating post-processing resources
> Creating sharpened texture of size 3056x3160
> Injecting PSSetSamplers into D3D11DeviceContext
> Creating replacement sampler for 000001C4FEFF42A0 with MIP LOD bias -0
> Creating replacement sampler for 0000000000000000 with MIP LOD bias -0
> Creating shader resource view for input texture 000001C4DBFE5978
> Texture has size 3056x3160 and format 28
> Creating replacement sampler for 000001C49008B060 with MIP LOD bias -0
> Creating replacement sampler for 000001C49008BCA0 with MIP LOD bias -0
> Creating replacement sampler for 000001C49008AF20 with MIP LOD bias -0



So the double radius is still present in fallout or was it working like normal? That texture size is normal. The game is rendering both eyes on a single image so you still have 2 eyes rendering at 3164x3948. I'm going to be out of town for a but if anyone else has a pimax and wants to test go for it and post the results. The games I saw success in were VRChat and Pavlov.

**Comment by BrziJoe** [comment]
I couldn´t see clear circles in Fallout, as with pp=on everything is blurry. Sorry.

Today I tried Skyrim VR; it is working excellent, just one circle per eye, but results are interesting:
The best "Center_Display" value for Pimax are:
1) +0.7 for small FOV 
2) +0.3 for normal FOV
3) -0.15 for large FOV

Only those values give good stereo overlap of sharper area.

One more thing, that will be interesting for @fholger also:
The default "MaximumRecommendedResolution" in steamvr.settings is 8192. That is actually limiter for biggest resolution (horizontal or vertical) that can be rendered. Steamvr does not ever render more, even if we set huge supersampling.
Once I tried with FSR huge supersampling and large FOV; that was way more then steamvr limiter, and  I got error in openvr_mod.log; 
*************************
Initializing hooks...
Requested interface IVRSystem_019
Injecting GetRecommendedRenderTargetSize into IVRSystem_019
Requested interface IVRCompositor_022
Injecting Submit into IVRCompositor_022
Creating post-processing resources
Input texture is in SRGB color space
textureContainsOnlyOneEye: 0
Creating upscaled texture of size 17456x5808
Failed (80070057): Creating upscaled texture

*************************

PS: The default "MaximumRecommendedResolution" can be changed in steamvr.settings, and I changed it to 16384 (recommended by Pimax). I do not know how much is a limit.

**Comment by Dazbii** [comment]
Ah, I should have checked other forks to see if someone else has already gotten on this before I did. I made some changes in my fork here but I haven't figured out how to build this project yet so I haven't actually tested if my stuff works lol. Either way, the math is a little different on mine, not sure if it's better but it might be worth a peek? https://github.com/Dazbme/openvr_fsr

Any idea when you might be submitting a pull request @RamesTheGeneric ? I saw you had one but then closed it, I'd love to start making use of this for my Pimax, but apparently a degree in computer science isn't enough to prepare me to use cmake and makefiles.

**Comment by RamesTheGeneric** [comment]
@Dazbme 
The first pull request I submitted was all out of wack from the lack of testing I did. I'll submit another once I can see it has the same compatibility as fholger's current build, when I get home, and get another graphics card in my PC (drop an f in the chat for my 2080ti). For building, my smooth highschool brain used cmake gui to make a visual studio 2019 solution and build it in there. Just check "is shared" or something like that. I have no idea how to use make files or what they even do.

**Comment by Dazbii** [comment]
Oh awesome, thanks for pointing me in the right direction, it didn't work building on Windows so I went straight to Linux and had a hell of a time there lol.

Anyway, my branch seems to work fine, here are some screenshots I took. All of these have radius 0.2, scale 0.59, and 1.0 sharpness:
This one has centreOffset=0.0, this is the default position.
![s059r020o000-c](https://user-images.githubusercontent.com/9468737/128612493-541b70ce-e9b2-47ed-80c7-46246412a5fd.png)

centreOffset=1.0 will move the circle all of the way to the middle edge of each eye:
![s059r020o100-c](https://user-images.githubusercontent.com/9468737/128612576-ecdef539-5790-4d0d-9d2e-7b1874619c9f.png)

centreOffset=0.5 puts it halfway between the center of each eye and the middle edge:
![s059r020o050-c](https://user-images.githubusercontent.com/9468737/128612610-2d06bdfb-ee2f-48f9-9510-71d0cb2d8a26.png)

centreOffset=-0.5 shows that negative values are also possible, moving the circle towards the outer edge of each eye, with 1 having the center of the circle directly on the outer edge. I don't see how this could be useful but the option is there.
![s059r020o-050-c](https://user-images.githubusercontent.com/9468737/128612643-25a8d16c-4483-40ed-8896-d648a1f4beb5.png)

@RamesTheGeneric Your changes also seem to work, though I think the math on yours makes it a little harder to adjust. Since the offset variable is in the denominator, it does not move linearly, it also has the potential to divide by zero if the user were to set the offset to 2 or -3. You can see what I mean about the non-linear movement here:
https://www.desmos.com/calculator/8n5ulakhxu
The vertical lines represent the center of each circle and the a variable represents the centreOffset, I have my math on the red and green and yours on the blue and black. x=-10 to 0 represents the left display while x=0 to 10 represents the right display. As you drag the slider for a around, you can see that yours slows down as the number gets more negative, never actually able to reach the middle. Though you have to disregard my lines for values below -1 as my intended range is -1 to 1. I think it may be a bit confusing for users to have the offset set to -100 vs -1000 not move the position much.

**Comment by RamesTheGeneric** [comment]
@Dazbme I see what you mean now. I thought mine made it to the edge but I guess not. Kinda hard for me to tell. I'll play around with yours and compare it to mine once I get the chance. Nice work👍

**Comment by fholger** [comment]
Please try the new v1.1 release. It should properly calculate the actual projection center, and you can also visualize the radius via the `debugMode` config option to verify.

**Comment by fholger** [comment]
I am going to assume this issue is fixed. Feel free to reopen if you feel there is something left to do here.

**Comment by BrziJoe** [comment]
@fholger your  v1.1 unfortunately does not fit Pimax canted displays; stereo overlap of sharper area is only partial. I tried it on IL-2 and Skyrim - same results.

I would like to try branch from @Dazbme if somebody make compiled versions. Thx

**Comment by RamesTheGeneric** [comment]
@BrziJoe I'll take a crack at building his today.

**Comment by RamesTheGeneric** [comment]
[DazbmeOpenvrFSR.zip](https://github.com/fholger/openvr_fsr/files/6988638/DazbmeOpenvrFSR.zip)

@BrziJoe Here it is, I haven't tried it out but everything else seems normal.

**Comment by BrziJoe** [comment]
thank you, I tried  DazbmeOpenvrFSR.zip , and it is working great - the settings are easy and intuitive. I will use it for Pimax.
@fholger if possible, I would like to see this branch in your main release also.
Thank you all of you guys in name of my pimax colleagues :)

**Comment by fholger** [comment]
I will need more data here. Specifically, what values are you using for Dazbme's branch, and what does the main release output as the "projection centers" in the log file? I also need more reports from other people.

The projection center is specifically calculated from the projection info that the headset provides, and as such, it should be more correct than any manually chosen offset.

**Comment by RamesTheGeneric** [comment]
[openvr_mod.log](https://github.com/fholger/openvr_fsr/files/6988987/openvr_mod.log)
I just tested the new build with debug mode on with both wide and normal fov settings and parallel projection off. It seems to place the upscaling area centered about where my eyes are. Seems to work great in pavlov and vrchat. Here's the log from the normal fov test in vrchat. 
@fholger

**Comment by BrziJoe** [comment]
The new branch with debug works with pimax, but only with parallel projections = on (pp=on).
PP=off (native pimax rendering) has wrong positioning of clear spots.

PP=on should be used only if game does not support modern engines / canted displays. It uses about 25/30% more resources, and should be avoided.

****************
Now about testing od Dazbme branch:
here are logs and applied settings for Pimax:
[test Dazbme.zip](https://github.com/fholger/openvr_fsr/files/6988998/test.Dazbme.zip)
Used settings:
pp=on
small fov     "centreOffset": 0.275,
normal fov     "centreOffset": 0.45,
large fov     "centreOffset": 0.675,
***********************
pp=off
small fov	"centreOffset": 0.1,
normal fov	"centreOffset": 0.25,
large fov	"centreOffset": 0.4,

**Comment by BrziJoe** [comment]
> I just tested the new build with debug mode on with both wide and normal fov settings and parallel projection off. It seems to place the upscaling area centered about where my eyes are.

@RamesTheGeneric can you please try with radius 0.1 and pp=off, bigger radius can misslead you.
I wish it was working for me, but it is not.

**Comment by RamesTheGeneric** [comment]
> > I just tested the new build with debug mode on with both wide and normal fov settings and parallel projection off. It seems to place the upscaling area centered about where my eyes are.
> 
> @RamesTheGeneric can you please try with radius 0.1 and pp=off, bigger radius can misslead you.
> I wish it was working for me, but it is not.

I'll try to test that tomorrow after classes but even if it's not perfect, it's close enough for me to switch off of my own branch.

**Comment by fholger** [comment]
Sorry, I need the logs from the 1.1 release, *not* the test branch. Specifically, I need  the calculated "projection centers" in comparison to the chosen settings of the test branch.

**Comment by BrziJoe** [comment]
> I need the logs from the 1.1 release

No problem, I have some spare time today :)
[test skyrim v1.1.zip](https://github.com/fholger/openvr_fsr/files/6990682/test.skyrim.v1.1.zip)

PS: take care that PP=off and PP=on are not comparable, it is another geometry.
PS2: again with large fov, and especially pp=on, I had too big horizontal resolution (ca hor 19000). I had to keep everything down just to make tests.

**Comment by fholger** [comment]
I will most likely need to do some experiments with a canted display to figure out the appropriate math. Unfortunately, I had to RMA my Index headset, so this will have to wait until it is back.

**Comment by BrziJoe** [comment]
Folgher, I was thinking, the center of view in Pimax (pp=off) is always same distance from inner edge (to the nose). That is same regardless of fov, as with different fov we change just outer edge limit (to the ears).
![3x PIMAX FOV](https://user-images.githubusercontent.com/35833650/129860436-25cf7988-1078-48c3-924a-39cae8cc7f75.png)

The difference is also 10 degrees in angle, from your calculation to real pimax center of view. 
Maybe you can use that..

**Comment by fholger** [comment]
I've tried to incorporate the canted angle into my calculations, but since I don't currently have a canted HMD, I can't really test or verify if those adjusted calculations do what they are supposed to. I'm attaching a test build here, I'd appreciate if someone could try and post the resulting logs from that. The chances that it actually works are not super high, but I added some additional log messages that would be helpful :)
[openvr_fsr_canted.zip](https://github.com/fholger/openvr_fsr/files/7022018/openvr_fsr_canted.zip)

**Comment by BrziJoe** [comment]
Unfortunately, it looks same as before:
![openvr_fsr_canted-v1](https://user-images.githubusercontent.com/35833650/130249587-f39bdce5-c533-422e-b240-b9c9144b3639.png)
[openvr_fsr_canted.log](https://github.com/fholger/openvr_fsr/files/7022249/openvr_fsr_canted.log)

**Comment by BrziJoe** [comment]
Wait, left eye is more-less ok, just right went to opposite side (to outer side, should go to inner side).

You made booth eyes more to the right this time.

**Comment by fholger** [comment]
Yeah, that's the kind of mistake that can happen when I can't test :) I may need logs for the other FOV settings, too, though. Just to see if the calculations even make sense for the reported values.

**Comment by BrziJoe** [comment]
All 4 fov logs:
[openvr_fsr_canted small.log](https://github.com/fholger/openvr_fsr/files/7022447/openvr_fsr_canted.small.log)
[openvr_fsr_canted large.log](https://github.com/fholger/openvr_fsr/files/7022448/openvr_fsr_canted.large.log)
[openvr_fsr_canted normal.log](https://github.com/fholger/openvr_fsr/files/7022449/openvr_fsr_canted.normal.log)
[openvr_fsr_canted potato.log](https://github.com/fholger/openvr_fsr/files/7022450/openvr_fsr_canted.potato.log)

**Comment by fholger** [comment]
Thanks. The calculated offsets are not a perfect match for those you provided with dazbme's build, but they are in the same ballpark. Right eye offset should hopefully be fixed in this build: 
[openvr_fsr_canted2.zip](https://github.com/fholger/openvr_fsr/files/7022701/openvr_fsr_canted2.zip)

**Comment by BrziJoe** [comment]
You almost there. There is still small mismatch.
And what is funny, if I choose really small foveated radius (0.02)
 the error is almost non existing. With larger radius (0.4 - 0.6), mismatch is bigger, an double circles are always visible.
(With radius 0.8 and bigger, I do not see any more circles edges between my eyes, so then it is "usable".)

[openvr_fsr_canted2 fov small pp off r06.log](https://github.com/fholger/openvr_fsr/files/7023056/openvr_fsr_canted2.fov.small.pp.off.r06.log)
[openvr_fsr_canted2 fov small pp off r01.log](https://github.com/fholger/openvr_fsr/files/7023058/openvr_fsr_canted2.fov.small.pp.off.r01.log)



I think that your center calculation is now correct, but something is wrong with drawing circles. Is that possible?


And why my findings are slightly different here and with Dazbme's build? Because with Dazbme´s I was looking close, really close to see difference, and then my look is more cross eyed.
With yours version there is existing debug mode, and I was easy testing with looking further away (as it was possible) = eyes are more parallel!
Unfortunately, fixed foveated rendering has fixed circle centers, and eyes changes ipd depending on distance to object. 
Do not worry for that.

**Comment by fholger** [comment]
I guess the question is if it is perhaps good enough? In normal play, you are not playing with the debug mode enabled, and the radius should be harder to notice directly. So if it is near enough, it shouldn't really be too distracting.

Drawing a non-circle could get complicated quite quickly, so I'd rather not want to touch that.

**Comment by BrziJoe** [comment]
You are right, during play it is mostly non existent. Maybe in some games/cases it is more visible. I will play more with your version to see how it is in longer sessions. thx!
Ps; I red that newer Pitools (Pimax driver) do not correct geometry right if somebody changes IPD. Maybe that is problem?

**Comment by BrziJoe** [comment]
Hey Fholger, I was playing last few days with latest version; it is good enough for Pimax, do not change it further. When in game, I totaly forgot on foveated rendering. Excellent work man :)

**Comment by fholger** [comment]
Canted optimizations are now officially released in v1.2.
