### ISSUE TITLE
FSR not... working?

### ISSUE THREAD

**Issue by WWWOWWWPL** [fholger/openvr_fsr#29]
I have a 1050ti nvidia GPU, so I'm usually below most pcvr games' specs. The GPU is probably my biggest bottleneck, as I have 16 gigabytes of ram and an Intel Core i5-7600k CPU, which I'd say is a pretty mediocre mid-range set if not for the graphics card. I saw this git and I was immediately interested, I decided to try it out on a game called VTOL VR. The results were... unexpected. The resolution was terrible, even when set to the ultra quality option. I could barely read text and the framerate seemed to be the same as before. At first I thought it might be an issue with the game; VTOL VR isn't listed in the wiki after all. I tried H3VR next, and the same problem persisted. I don't know if I'm doing something wrong or if both of these games don't work with FSR. 

VTOL VR FSR Log:
[openvr_mod.log](https://github.com/fholger/openvr_fsr/files/6850839/openvr_mod.log)

H3VR FSR Log:
[openvr_mod.log](https://github.com/fholger/openvr_fsr/files/6850845/openvr_mod.log)

**Comment by fholger** [comment]
The logs suggest that the renderScale was set to 0.59, which would be the "balanced" mode, not "ultra quality". That would definitely explain why the resolution is terrible.

As for framerate: FSR upsampling has a cost that, unfortunately, depends on the target resolution and your GPU. It is possible that with your GPU, the cost for the upsampling to the selected target resolution is simply too high and may offset any gains from the lower render resolution. You could try a lower target resolution, but a higher renderScale setting, that might perhaps yield better results. But it's entirely possible that FSR just isn't useful for you.

**Comment by WWWOWWWPL** [comment]
> The logs suggest that the renderScale was set to 0.59, which would be the "balanced" mode, not "ultra quality". That would definitely explain why the resolution is terrible.
> 
> As for framerate: FSR upsampling has a cost that, unfortunately, depends on the target resolution and your GPU. It is possible that with your GPU, the cost for the upsampling to the selected target resolution is simply too high and may offset any gains from the lower render resolution. You could try a lower target resolution, but a higher renderScale setting, that might perhaps yield better results. But it's entirely possible that FSR just isn't useful for you.

Thanks for the quick response!
I'll try lowering my steamvr resolution and increasing renderscale, as for the visuals I previously set the renderscale to ultra quality, just in a different session played earlier. Ultra quality graphics don't bother me that much, guess I'll just have to deal with it.
