### ISSUE TITLE
Projection/inclination correction (so far only observed in IL-2 Sturmovik)

### ISSUE THREAD

**Issue by firdimigdi** [fholger/openvr_fsr#3]
Thanks for your work - I know it's only meant for some specific games, however:

I gave it a spin in IL2 Sturmovik using an HP Reverb G2 and although the game loads fine and FSR is doing its thing, there seems to be some sort of problem in the projection of the image - looks like the images on the screens are too wide-apart or something and there seems to be some slight distortion when pitching the view. 

Any tips on what to check on correcting this?

**Comment by fholger** [comment]
Hm. Does the game have a built-in resolution scale, possibly even a dynamic resolution scaler? If so, you could try disabling those and see if that makes a difference. Other than that, I don't have any obvious ideas.

**Comment by firdimigdi** [comment]
It has a dynamic resolution scaler but it is disabled as far as I can tell. 
I'll have a poke around later and see if I can figure it out - sadly I do not have any of the games this mod is meant for to test it on and make sure it's not an issue related to the WMR stuff (all of it is set to the HMD's native/max resolution). 

Thanks for your time!

**Comment by jordanpucela** [comment]
I just tried IL2 and even lowering the dynamic resolution to a minimum, it also happens to me that it looks double. Let's see if it can be solved in a future version. Keep up your excellent work

**Comment by fholger** [comment]
I'm afraid I'd have to see a frame grab to figure out what is going on here, but I don't own the game. If anyone who owns the game knows how to use e.g. RenderDoc or nSight, give me a shout.

**Comment by fearlessfrog** [comment]
Here's a RenderDoc captured frame from the initial menu, that shows the projection offset being wonky. Let me know if you need a plain export or anything else. Thank you for openvr_fsr btw!

https://mega.nz/file/gswSFBJJ#bEJ-0H-gyu3yM-OcrpI2FC2movM2hwDdjOFHqLMxUFI

**Comment by DTA666-sys** [comment]
> I'm afraid I'd have to see a frame grab to figure out what is going on here, but I don't own the game. If anyone who owns the game knows how to use e.g. RenderDoc or nSight, give me a shout.

I'll gift it to you if you want, thanks for taking the time to look at it.

**Comment by fholger** [comment]
Thanks for the frame @fearlessfrog 
I think I may have a vague idea what's happening.

**Comment by jcenzano** [comment]
still happening with the new 1.2 version.
I hope you can correct this issue because in DCS works flawlessly an the performance boost is very much welcome.

@fholger thank you very much for this

**Comment by fholger** [comment]
Could you try this build?
[openvr_fsr_il2_test.zip](https://github.com/fholger/openvr_fsr/files/6787446/openvr_fsr_il2_test.zip)

**Comment by fearlessfrog** [comment]
That works great for me - a pretty solid 10ms just with default settings. Thanks for looking at it so fast.

**Comment by DTA666-sys** [comment]
> Could you try this build?
> [openvr_fsr_il2_test.zip](https://github.com/fholger/openvr_fsr/files/6787446/openvr_fsr_il2_test.zip)

You are a legend.

**Comment by firdimigdi** [comment]
I can confirm this works on my end as well. Many thanks  @fholger!

**Comment by jcenzano** [comment]
it works for me too. Thank you again!!!

**Comment by firdimigdi** [comment]
I would close this issue however it gets visibility for the link to the fixed build; will do so as soon as it's integrated in the public release. Thanks again for your time @fholger !
