### ISSUE TITLE
Not an issue but I don't know where to ask this

### ISSUE THREAD

**Issue by alzahhar3** [fholger/openvr_fsr#30]
is there a discord for this mod? Or a community list where I can see which games work/work with caveats/not work that I can also help build? 

Also apologies for posting this as an issue

**Comment by fholger** [comment]
There's the beginning of a list in the wiki: https://github.com/fholger/openvr_fsr/wiki

No dedicated Discord for the mod. You could try one of the general Virtual Reality discords, I guess.

**Comment by alzahhar3** [comment]
I am hoping there will be a community list, there are so many games out there that a few people can't possibly test them all on a bunch of different HMDs. Hopefully you guys make one or one of the discords.

**Comment by fholger** [comment]
The Wiki can be edited by the public, so as long as people collect their findings there, it *is* a community list :)

**Comment by alzahhar3** [comment]
I... did not know that :D, I'll test some of my games and add to it soon then!
