### ISSUE TITLE
Vox Machinae Experiences Incorrect Eye Convergence

### ISSUE THREAD

**Issue by syixxs** [fholger/openvr_fsr#31]
The FSR dll appears to work just fine in terms of visuals, but the eye convergence is off-set too far apart when used, resulting in a double-image effect. Using RC2. Immediately remedied by switching back to the standard openvr_api.dll.

**Comment by syixxs** [comment]
Also just noted this same behavior with IL-2 Sturmovik: Battle of Stalingrad. Should this be reported as an additional issue or included as the same?

**Comment by fholger** [comment]
Given that multiple users have reported success with IL-2, this can't be a general problem. What headset are you using?

**Comment by syixxs** [comment]
I'm using a Reverb G2.

**Comment by syixxs** [comment]
Have any other users reading this thread noted convergence issues with the G2 in these, or other, games? @fholger is there any other config setting I might add or adjust to further experiment or test on this? I'm stopped in terms of further troubleshooting as I don't have levers I'm aware of beyond scale and sharpness.

**Comment by fholger** [comment]
You can try setting the `radius` parameter to e.g. 2. This will disable the fixed foveated optimization, but it's also the only setting that could potentially cause issues with mismatched eye pictures.

Other than that, you could check if the games you are testing feature dynamic resolution adjustments. Those might not play too well with the FSR mod, so you might want to disable them.

**Comment by syixxs** [comment]
> You can try setting the `radius` parameter to e.g. 2.

Pardon my ignorance on the subject as this is my first foray into the OVR API, but where can I find the correct syntax and description of values for `radius` and others? I'm digging through the OVR API wiki linked at the bottom of your readme but haven't had any luck finding it so far.

**Comment by fholger** [comment]
Oh, you went too far down. The section at the bottom about the "OpenVR SDK" is the original readme from where I forked the project. It has no relevance to any of the config settings for this mod. The three main settings are explained before that in the readme and also via comments in the actual config file. I guess the ranges are kind of missing for the radius. But for radius, for it to actually do something, you'd have to put a value below 1, with lower values applying FSR to a smaller part of the image. And setting it to something high (like 2 or above) will effectively disable the optimization.

**Comment by rhylos** [comment]
@fholger perhaps an optional semi transparent overlay can be coded in to help with setting a radius value.

I'm toying with decent results using the radius to upscale using values such as 3.0 for renderScale. Treating this as a poor mans VRSS for games that don't have it. Lowering SteamVR's SS a bit and upping the renderScale with radius at 0.3'ish. I believe I have to watch VRAM a bit more than GPU use in this use case.

**Comment by syixxs** [comment]
Excellent, thank you! Setting `radius` to 2 definitely resolves the double-vision in Vox Machinae. Perhaps an action for this issue would be to add the following snippet to the sample configuration file?

``` 
// To mitigate overhead of FSR use 'radius' for a sort of "fixed foveated" optimization where only the center
//of the image is upscaled by the more expensive FSR algorithm, while the edges are upscaled by cheaper
//bilinear sampling. If <=1, will apply FSR to a smaller portion of the image. If >2, will disable this feature and
//may fix issues with eye convergence (double vision).
//"Fixed foveated" => 1
//Disable radius => 2
```

I am also happy to report that this resolved the issue with IL-2, as well. I'll updated entries in the wiki with the latest. Please consider this one closed! Thank you for the help.
