### ISSUE TITLE
Medal of Honor Above and Beyond no upscale

### ISSUE THREAD

**Issue by kinemitor** [fholger/openvr_fsr#32]
here is the log
[openvr_mod.log](https://github.com/fholger/openvr_fsr/files/6859608/openvr_mod.log)

**Comment by fholger** [comment]
Log looks fine, the mod is definitely doing something. Why do you say there is no upscale? What specifically is happening or not happening?

**Comment by kinemitor** [comment]
After playing with the mod at 1823p with Target render at 1404p I removed the mod an lowered the resolution to 1404p to see how much better was the modded version over the same target render but to my surprise the native 1404 looked a lot better than the 1823p fsr mod

**Comment by fholger** [comment]
I'm afraid I don't have the game, so I can't test this. I'll need more details. How exactly did the mod look worse? What specifically did you notice?

**Comment by kinemitor** [comment]
while the low res native was too blurry as expected, the game menu looked as expected but when the mod is active game menu gets a lot of jaggy edges, like if missing some aliasing, now in game I don't notice a problem, so my theory is that this implementation of fsr is being placed over the UI and that should not happen, maybe this is not fixable in a single dll mod, if that is what is happening the this game is one of those "partially compatible"

edit: there is a way to see what I mean in other games that support steamvr but aren't launched with steam client, some games from oculus store can do this if you launch their exe directly. 
put this mod in one of those games, set 0.5 scale resolution target to make it very niticeable
close steam
then launch the exe
steamvr will open without steam and you will see a very ugly steamvr interface

**Comment by fholger** [comment]
Yes, that's the gist of it. This mod can only be applied at the very end, after UI and any post-processing effect, whereas in a native integration FSR should be applied before UI and post-processing. Whether or not that's a problem depends very much on the particular game. But there is nothing I can do about it, either way.
