### ISSUE TITLE
What else do i need to get this running?

### ISSUE THREAD

**Issue by X3roxx** [fholger/openvr_fsr#37]
Maybe a dumb question....do i need to download something from the AMD Site? 
I'm a bit lost at the moment, i have a RTX 2070S and want to use FSR
Already changed the files in the SkyrimVR  folder but i don't think it's done with just the 2 files, no?

**Comment by fholger** [comment]
It is, actually. You can check if it's working by looking for the `openvr_mod.log` file. It will be created if the mod is active.

**Comment by fholger** [comment]
I'm assuming this is answered.
