### ISSUE TITLE
VRChat - Changes colours

### ISSUE THREAD

**Issue by Valve-Anti-Cheat** [fholger/openvr_fsr#38]
Hi there!

Tried this with VRChat and SteamVR. Works perfectly fine besides the colours, it makes it extremely bright/low contrast/low saturation - doesn't look great and it does make it unplayable. Any known fix?

Regards,
VAC

**Comment by fholger** [comment]
I need to see the openvr_mod.log.

**Comment by Valve-Anti-Cheat** [comment]
> I need to see the openvr_mod.log.

I will post as soon as I get home! xoxo

**Comment by fholger** [comment]
Is this still an issue with the latest release? If so, I still need that log file...

**Comment by JulianGro** [comment]
Running openvr_fsr with VRChat and no issues on my end.

**Comment by fholger** [comment]
Thanks! I'll consider this one closed, then.
