### ISSUE TITLE
Onward not working

### ISSUE THREAD

**Issue by GreenMan36** [fholger/openvr_fsr#39]
[Player.log](https://github.com/fholger/openvr_fsr/files/6899951/Player.log)
I've cleaned the log spam a bit and noted it down.

I've tried both normal mode and legacy mode but both don't seem to work.
Possibly due to EAC?  (Easy Anti Cheat)
However, removing the EAC dll gives the same log and errors.

It goes till the Downpour logo and then stays black. No crashes.

**Comment by fholger** [comment]
Sounds like it can't load the DLL. This could e.g. happen if a game is x86, because the DLL is built for x64. But I'm assuming Onward is x64, anything else would be surprising.

It's also possible that Onward or the Unity engine version uses a slightly custom openvr build that my replacement DLL is not compatible with.

**Comment by sycspysycspy** [comment]
However Onward 1.7 has no problem with the dll. I have tested myself.

**Comment by RastadasPT** [comment]
Tested as of today, 31st of August, not working in booth stable and rolled back 1.7 versions of the game. Probably anti-cheat related because the error message is saying that the openvr.dll is not original.

**Comment by sycspysycspy** [comment]
> 
> 
> Tested as of today, 31st of August, not working in booth stable and rolled back 1.7 versions of the game. Probably anti-cheat related because the error message is saying that the openvr.dll is not original.

I just played 1.7 with this DLL 2 days ago, maybe it's due to I switched to 1.7 a very long time ago and the anti cheat is differnt?

My easyanticheat is 4.0.0.0 as seen in the EasyAntiCheat_Setup.exe properties/detail

**Comment by Zman2024** [comment]
For me, FSR works on 1.7 _singleplayer_ but when i join multiplayer i cant hear my teammates and eventually disconnects me from the lobby. This happens even with EAC off (using the "launch for 1.7" option in steam)

**Comment by GreenMan36** [comment]
> 
> 
> For me, FSR works on 1.7 _singleplayer_ but when i join multiplayer i cant hear my teammates and eventually disconnects me from the lobby. This happens even with EAC off (using the "launch for 1.7" option in steam)

That might actually be a bug in the old lobby system.
They did a massive rewrite on the newer versions of the game just to fix all the issues with disconnecting and hearing.

**Comment by sycspysycspy** [comment]
> For me, FSR works on 1.7 _singleplayer_ but when i join multiplayer i cant hear my teammates and eventually disconnects me from the lobby. This happens even with EAC off (using the "launch for 1.7" option in steam)

I can play multiplayer with no issue. Launch for 1.7 still invoke the EAC I think.

**Comment by sycspysycspy** [comment]
> Tested as of today, 31st of August, not working in booth stable and rolled back 1.7 versions of the game. Probably anti-cheat related because the error message is saying that the openvr.dll is not original.

I encountered this issue as well last week after I apply the latest version, but as I rollback to 1.2 version it works again.

**Comment by GreenMan36** [comment]
They will not allow for modification of `openvr.dll` and there are no plans to do so in the future.

OpenVR-FSR will not work on Onward now or in the future. Allowing modification would be a massive entry-point for hacks and seeing this is a competitive game, there's no way they're changing their minds.
