### ISSUE TITLE
Is this possible to apply on MSFS2020?

### ISSUE THREAD

**Issue by avateck** [fholger/openvr_fsr#43]
It's working very well on the some games I'm playing.

However I tried apply on MSFS2020 but failed.

It doesn't have openvr_api.dll in folder but the only have openxr file.

Is that possible to apply to MSFS2020?

**Comment by fholger** [comment]
No, OpenVR is a hard requirement for this mod, I'm afraid.

**Comment by avateck** [comment]
> No, OpenVR is a hard requirement for this mod, I'm afraid.

thanks for reply mate.
