### ISSUE TITLE
AMS2 works excellently with full detail via the Oculus Link :-D

### ISSUE THREAD

**Issue by Mavy1704** [fholger/openvr_fsr#45]
AMS2 works excellently with full detail via the Oculus Link with the AMD 6900XT and a 5800X ..... 90 FPS without problems (0.77 FSR).  When I try to play wirelessly via Virtual Desktop, I get an error message.

 Thanks for the MOD :-D

**Comment by fholger** [comment]
What error?

**Comment by Mavy1704** [comment]
A Picture in a link: https://mega.nz/file/OgkGSL5Z#-j1OkCjJjx5X7xdnHSkPrAv4PtR102-C3gADyBMlXvY

**Comment by Mavy1704** [comment]
It worked 1-2 weeks ago.  Can of course also be due to the update of AMS2 or other software.

**Comment by fholger** [comment]
Was that with the same version of the FSR mod? If not, you may want to retest with an older version.
The error is unfortunately not helpful. Does it produce a log file (openvr_mod.log)? If so, please post its contents.

**Comment by Mavy1704** [comment]
I have removed your mod now and the bug is still there.  I suspect that it is due to the new update of SteamVR or AMS2.  Unfortunately there is no openvr_mod.log because the error is probably not to be found there?  Greetings Thomas

**Comment by ludwig6666** [comment]
> AMS2 works excellently with full detail via the Oculus Link with the AMD 6900XT and a 5800X ..... 90 FPS without problems (0.77 FSR). When I try to play wirelessly via Virtual Desktop, I get an error message.
> 
> Thanks for the MOD :-D

What version of the mod did you use for AMS2?

**Comment by Mavy1704** [comment]
The newest 1.2.2.0.1753.AVX....with Steam.

**Comment by ludwig6666** [comment]
> The newest 1.2.2.0.1753.AVX....with Steam.

in my case ACC gained 15% FPS at the same quality but the mod doesn't work on AMS2 neither PC2. Anyway this is a huge contribution! @fholger congratulations and really thanks a lot!

**Comment by fholger** [comment]
Given that the original report/title wasn't really an issue, I'm closing this one. Feel free to open a new issue if there's still something to be resolved :)
