### ISSUE TITLE
The Forest could launch without any issue

### ISSUE THREAD

**Issue by sycspysycspy** [fholger/openvr_fsr#48]
The game could start without any issue but I don't notice any improvoment... How can you tell if the API is working as intended?

**Comment by fholger** [comment]
Generally, by checking the openvr_mod.log. If it does not contain lines like "creating resources" or "creating sampler", it's probably not working. You can upload the log here if you are unsure.

**Comment by sycspysycspy** [comment]
> Generally, by checking the openvr_mod.log. If it does not contain lines like "creating resources" or "creating sampler", it's probably not working. You can upload the log here if you are unsure.

It indeed contains lines like that maybe I will tweak the settings and see how. Thanks for your amazing work.

**Comment by fholger** [comment]
You can always set `renderScale` to something ridiculously low, like 0.1. You'd definitely notice that if it's working :)
