### ISSUE TITLE
Only renders left eye correctly in self developed title

### ISSUE THREAD

**Issue by qlee01** [fholger/openvr_fsr#49]
Hey, currently developing with Unity / SteamVR. Using this lib on a build has the efffect that the right eye is not rendered correctly, it seems to be complete out of perspective and does  not match at all with the left eye. Anyhing I can try to work around this ?

**Comment by fholger** [comment]
First thing to try is to set `radius` to 2.

**Comment by qlee01** [comment]
I tried, but it did not change anything, I also tried all other params, the only thing which helped was turning it off  with the first param;)

**Comment by fholger** [comment]
Then I'm afraid I don't really have any other tips to offer at this point. If you are familiar with e.g. RenderDoc or nSight, you could try to take a frame capture and investigate what's happening with the FSR application and the frame submission.

**Comment by fholger** [comment]
Is it possible you placed the DLL in the wrong place? It must replace the existing openvr_api.dll in the Plugins subdirectory for Unity builds. If you place it directly beside the executable, for example, then weird things are known to happen and might explain the issue.
