### ISSUE TITLE
Incompatibility with Open Composite

### ISSUE THREAD

**Issue by ArcaneFumble** [fholger/openvr_fsr#5]
Any chance it might be possible to build in compatibility with open composite? 

https://gitlab.com/znixian/OpenOVR

Both of you are using openvr_api.dll as your hook so right now it's one or the other. For a lot of us folks on Oculus, Open Composite is really a lifesaver for the few games it supports Skyrim and Fallout being chief among them.

**Comment by fholger** [comment]
I can't promise anything. I am exploring a different method of injection to possibly get it to work with games like Star Wars: Squadrons and HL: Alyx, but whether it would also work with OpenComposite is anyone's guess.

**Comment by ArcaneFumble** [comment]
That's fantastic. Figure if you at least know about it you might stumble across some easy way to make things click. Appreciate the reply and just amazing work getting something like this sorted for all us ungrateful folks!
