### ISSUE TITLE
Upscaling not happening at all?

### ISSUE THREAD

**Issue by CircuitLord** [fholger/openvr_fsr#50]
Hello!

I've been having some difficulty getting this to run properly (using an RTX 3080 and Index). I'm convinced the DLL is working, because the "renderScale" value in the config is affecting the output resolution, although FSR does not appear to be occuring at all. (wasn't seeing anything weird in the log file either)

I've tried messing with the radius setting, and I've been unable to destinguish any difference between the center and edges of the image (even when looking at it in the deskop view), it all just looks low resolution.

I've tested this with Revive (by swapping it's DLL instead of a specific game), and in a basic example with Beat Saber, and have gotten the same results.

Is it possible I'm doing something wrong, or maybe just over thinking how good FSR should look? So far it's just looked identical as if I were to just run at that resolution.

Thanks!

**Comment by RamesTheGeneric** [comment]
Make sure that your settings are formatted like "0.3" or "0.9" instead of ".3" or ".9".

**Comment by fholger** [comment]
It's hard to say, but I would suggest not using Revive for testing, and picking some other SteamVR-native game with more image detail than Beat Saber. Also, forget the mirror; the games' own mirrors almost certainly do not go through FSR at all, and even with the SteamVR mirror view it may be hard to see.

If you possess them, Skyrim or Fallout would make for ideal test candidates, because they produce a rather blurry image by default, and you should be able to spot FSR's sharpening, at least, fairly easily.

**Comment by CircuitLord** [comment]
> 
> 
> Make sure that your settings are formatted like "0.3" or "0.9" instead of ".3" or ".9".

They're like that, yeah.



> 
> 
> It's hard to say, but I would suggest not using Revive for testing, and picking some other SteamVR-native game with more image detail than Beat Saber. Also, forget the mirror; the games' own mirrors almost certainly do not go through FSR at all, and even with the SteamVR mirror view it may be hard to see.
> 
> If you possess them, Skyrim or Fallout would make for ideal test candidates, because they produce a rather blurry image by default, and you should be able to spot FSR's sharpening, at least, fairly easily.

When I said mirror I meant the SteamVR View yeah.

I'll give it a shot in Skyrim VR and see if I can get any better results ^_^

**Comment by malzergski** [comment]
I have the exact same problem with VRChat and Beat Saber, the only two I've tested for now. The DLL seems to be working fine, no errors in the log file, though it's been only reducing the game's resolution without upscaling it.
Edit: oh and I'm using a WMR headset and a Vega 56.

**Comment by Cless-Aurion** [comment]
I have the exact same problem too, but with Elite Dangerous. It seems to work for some people though...? I'm using a 1070.

**Comment by WWWOWWWPL** [comment]
It seems that I'm getting a similar problem too. I tested it in H3VR and VTOL VR. The downscaling part of FSR works, but the upscaling doesn't seem to be there, it was like playing on a lowered res. I ran both games on amd's ultra quality, I have a 1050ti GPU and an i5-7600k 3.8ghz CPU

**Comment by fholger** [comment]
How exactly are you determining that upscaling is not happening?

You could also try the new v1.1 release, enable debug mode and set a fairly small `radius` that should then be visible in the headset.

**Comment by CircuitLord** [comment]
Just tried 1.1 in Boneworks and everything appears to be working now, I can see the radius that's getting sharpened, and the image quality is actually getting improved. Debug mode is also super helpful.

**Comment by Cless-Aurion** [comment]
Yup, confirmed the update fixed that issue!
