### ISSUE TITLE
Can't get to work in vr chat

### ISSUE THREAD

**Issue by RedHawk989** [fholger/openvr_fsr#51]
Wont work in vr chat but works great in other games like beatsaber. The log file appears normal to me but It isn't really on.

**Comment by ni1chigo2115** [comment]
There may be something to do with the fact that the update has centralized the functions into OVRPlugin.
By the same logic, it should not work in ohshape either.

**Comment by Huskehn** [comment]
This was working for me in the previous VRChat build, but now that the game has updated to use Unity 2019, I can't seem to get it to work. I tried changing "radius" to 2.0, "applyMIPBias" to false, does not seem to make a difference. I also tried changing "renderScale" and it doesn't seem to apply. Log: [openvr_mod.log](https://github.com/fholger/openvr_fsr/files/6937250/openvr_mod.log)

Edit: [This build of ReShade](https://github.com/fholger/reshade/releases/tag/openvr_alpha2) does work for me in VRChat though, so at least I can still use CAS. Thank you very much for making these by the way, CAS/FSR is so great for VR.

**Comment by tw1l1ght** [comment]
>  [This build of ReShade](https://github.com/fholger/reshade/releases/tag/openvr_alpha2) does work for me in VRChat though, so at least I can still use CAS.

Unless you bring Udon & video/mediaplayers into the mix - those are broken for me: video plays but you get no audio & GPU load skyrockets (imo the default audiodevice isnt picked up/adressed anymore)  :|

**Comment by ni1chigo2115** [comment]
It is not a good report for me that there is a problem with reshade.
MSAA has a very high load and without MSAA it is difficult to stay in VRC properly with jaggies.
If FXAA equivalent was provided in VRC, I would not be uncomfortable to stay in VRC for a long time without MSAA.

**Comment by tw1l1ght** [comment]
> If FXAA equivalent was provided in VRC, I would not be uncomfortable to stay in VRC for a long time without MSAA.

until these bugs are fixed you could try enabling FXAA (and or the other available modes besides MSAA) via application-profiles in nvidia controlpanel

**Comment by RamesTheGeneric** [comment]
I know the new update added an x86_64 folder in the plugins folder. That's where you should put the dll now.

**Comment by RedHawk989** [comment]
> I know the new update added an x86_64 folder in the plugins folder. That's where you should put the dll now.

this works, thanks.

**Comment by fholger** [comment]
I assume this is resolved, then.
