### ISSUE TITLE
How do you know its working. Is it working?

### ISSUE THREAD

**Issue by tedats** [fholger/openvr_fsr#54]
Sorry but how do I know if its on and working? 

Thanks!

**Comment by sycspysycspy** [comment]
Generally, by checking the openvr_mod.log. If it does not contain lines like "creating resources" or "creating sampler", it's probably not working. You can upload the log here if you are unsure. You can always set renderScale to something ridiculously low, like 0.1. You'd definitely notice that if it's working :)  - quoted from fholger.

**Comment by tedats** [comment]
Nice one thanks! I would infer that no log = it isn't working lol. Was trying with Elite Dangerous through Steam but I guess it isn't working. I'm assuming the log gets created when it's launched as I've not manually put that into any of the games. I think that's my answer anyways cheers!

**Comment by sycspysycspy** [comment]
I guess you might did something wrong. Did you replace the openvr_api.dll in the game folder? Elite Dangerous is suppose to be supported as mentioned in the wiki. 

steamapps\common\Elite Dangerous\Products\elite-dangerous-odyssey-64\Openvr\win64

**Comment by tedats** [comment]
I'll have another try today. I'm trying with Horizons which I don't think is officially supported. I did like you said when trying. I'll give it another shot today and see how goes. Will report back and maybe get the new DLC to try the officially supported implementation

**Comment by tedats** [comment]
The new DLC is officially supported but not sure if that applies to VR. I was trying on the base game. I'll try again, and also dl the dlc to see if that works.

**Comment by GreenMan36** [comment]
You can also set the resolution to like ``0.1`` and if it looks like garbage pixels, its working.

**Comment by tedats** [comment]
Okay yep it jst isn't working on the base game. Tried it at 0.1 like you said and looked the same as it did. Tried the new dlc in the options and wasn't hugely impressed tbh but at least I know how it might compare if it did work on the base game. Initially I think I preferred their regular super sampling when it comes to fps/visual quality balance.
