### ISSUE TITLE
Flight Simulator 2020

### ISSUE THREAD

**Issue by ASchneiderBR** [fholger/openvr_fsr#57]
Hello guys!

Just want to say: @fholger, thank you very much for this project, this is simply incredible! Amazing work.

Have you guys made it to work with Flight Simulator 2020? This would be a MAJOR enhancement, since FS2020 is the most demanding game to this date.

This would help me and so many people.

Thank you!

**Comment by fholger** [comment]
Unfortunately, Flight Simulator uses OpenXR, not OpenVR. This mod is only for OpenVR games and will therefore never support FS2020. I might do an OpenXR mod in the future, but the effort is significantly higher than for OpenVR, and right now there are not enough games using it to be worth that effort (for me).
