### ISSUE TITLE
No Upscaling seemingly taking place in SkyrimVR as of openvr_fsr 1.0

### ISSUE THREAD

**Issue by JoaGuevara** [fholger/openvr_fsr#58]
One weird thing though, if I go to SteamVR settings and reduce the resolution to the minimum (20%) which is about 1200x1200 (I have a Quest 2) then the game still looks sharp as full resolution. I think it may be some ini parameter or maybe a mod, or SKSE hardwiring the resolution to the highest, but this phenomenon doesn't happen without Openvr_fsr installed.

**Comment by fholger** [comment]
Post the openvr_mod.log, please.

**Comment by JoaGuevara** [comment]
Initializing hooks...
Requested interface IVRSystem_019
Injecting GetRecommendedRenderTargetSize into IVRSystem_019
Requested interface IVRCompositor_022
Injecting Submit into IVRCompositor_022
Requested interface IVRSettings_002
Creating post-processing resources
Input texture is in SRGB color space
Creating upscaled texture of size 8776x4438
Creating sharpened texture of size 8776x4438
Injecting PSSetSamplers into D3D11DeviceContext
Creating replacement sampler for 0000027F314A3020 with MIP LOD bias -0.376967
Creating replacement sampler for 0000027F314A57A0 with MIP LOD bias -0.376967
Creating replacement sampler for 0000027F314A5C20 with MIP LOD bias -0.376967
Creating shader resource view for input texture 0000027E3E547578
Texture has size 6758x3418 and format 28
Requested interface IVRRenderModels_005
Creating replacement sampler for 0000000000000000 with MIP LOD bias -0.376967
Creating replacement sampler for 0000027E0AE4F460 with MIP LOD bias -0.376967
Creating replacement sampler for 0000027E481211E0 with MIP LOD bias -0.376967
Creating replacement sampler for 0000027F314A34A0 with MIP LOD bias -0.376967
Creating replacement sampler for 0000027F314A62E0 with MIP LOD bias -0.376967
Creating replacement sampler for 0000027F314A2960 with MIP LOD bias -0.376967
Creating replacement sampler for 0000027F314A2860 with MIP LOD bias -0.376967
Creating replacement sampler for 0000027F314A75E0 with MIP LOD bias -0.376967


**(Edited because I made a mistake)**

**Comment by fholger** [comment]
Well, the mod is active and working, however, the resolutions appear off. The game is rendering to 6758x3418 (both eyes combined) and then it's upscaled to 8776x4438. Those resolutions are ridiculously high, which is why you probably can't observe any difference. It definitely appears like it's not honouring your SteamVR settings. Could be that you have supersampling active in the game itself, or possibly in the Oculus runtime.

Does it render to the low 20% resolution without the mod active? If not, I think your issue lies somewhere else.

**Comment by fholger** [comment]
I don't think there is an issue in the mod here, so I'm going to close this. Feel free to reopen if you have further information.
