### ISSUE TITLE
Missing source files "shader_fsr_easu.h" and "shader_fsr_rcas.h"?

### ISSUE THREAD

**Issue by Raicuparta** [fholger/openvr_fsr#59]
Seems like your source code is missing these. Are they supposed to come from somewhere else?

**Comment by fholger** [comment]
They are auto-generated during compilation. They contain the compiled bytecode of the compute shaders as generated by the DXBC compiler.

**Comment by Raicuparta** [comment]
Thanks for the quick answer. My problem is that trying to build via cmake gives me an error saying those .h files are missing. If it's not too much problem, could you tell me how to compile it properly?

**Comment by fholger** [comment]
You need to use CMake to generate Visual Studio project files. There isn't really anything else to it, but the auto compilation of the shaders won't work outside of Visual Studio.

**Comment by Raicuparta** [comment]
What I did was open the directory in Visual Studio, and it detects CMakeLists.txt and generates the VS files. But trying to build still gives the same missing files error :/

**Comment by fholger** [comment]
Try actually generating VS project files via CMake. It's possible that the integrated CMake support is not sufficient.

**Comment by Raicuparta** [comment]
Yupp, that worked. Thanks!

**Comment by AltoRetrato** [comment]
Hi there!

Could you tell me what commands are required to build the DLL?

I installed Visual Studio 2022 and used cmake, but it only generates a .lib file:
```
cd src & mkdir _build & cd _build
cmake ..
cmake --build .
```
Output:
```
  [...]
  Generating Code...
  openvr_api.vcxproj -> C:\openvr_fsr-fsr_v2.0\src\_build\Debug\openvr_api.lib
  Building Custom Rule C:/openvr_fsr-fsr_v2.0/src/CMakeLists.txt
```
I get the same result when opening openvr_api.vcxproj and building from the Visual Studio IDE.

With `cmake . -D BUILD_SHARED=1 & cmake --build .` (in the `src` folder):
```
  Generating Code...
     Creating library C:/openvr_fsr-fsr_v2.0/src/Debug/openvr_api.lib and object C:/openvr_fsr-fsr_v2.0/src/Debug/openvr_api.exp
LINK : warning LNK4217: symbol 'VR_GetGenericInterface' defined in 'openvr_api_public.obj' is imported by 'PostProcessor.obj'
 in function '"void __cdecl vr::CalculateProjectionCenter(enum vr::EVREye,float &,float &)" (?CalculateProjectionCenter@vr@@YAXW4EVREye@1@AEAM1@Z)' [C:\openvr_fsr-fsr_v2.0\src\openvr_api.vcxproj]
openvr_api_public.obj : error LNK2019: unresolved external symbol "void __cdecl vr::CleanupInternalInterfaces(void)" (?CleanupInternalInterfaces@vr@@YAXXZ) referenced in function VR_ShutdownInternal [C:\openvr_fsr-fsr_v2.0\src\openvr_api.vcxproj]
C:\openvr_fsr-fsr_v2.0\src\Debug\openvr_api.dll : fatal error LNK1120: 1 unresolved externals [C:\openvr_fsr-fsr_v2.0\src\openvr_api.vcxproj]
```

**Comment by fholger** [comment]
`BUILD_SHARED` must be enabled. Aside from that, no clue. I've never tried to use the command line to build the project. All I can say is that using the CMake GUI to create a sln file for VS 2022 (with BUILD_SHARED enabled) builds fine for me.

**Comment by AltoRetrato** [comment]
I figured out I needed to define VR_API_PUBLIC. So, to build it from the command line:

If you don't have cmake.exe in your path: ```set PATH=C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\;%PATH%```

```
cd src & mkdir _build & cd _build
set CL=/DVR_API_PUBLIC=1
cmake .. -D BUILD_SHARED=1
cmake --build .
```

That will build with config `Debug`. Alternatively, for `Release`, change the last command to:
```
cmake --build . --config Release
```
