### ISSUE TITLE
Do you have to activate it in any way in each game or in Steam VR?

### ISSUE THREAD

**Issue by jordanpucela** [fholger/openvr_fsr#6]
Hi, I must be doing something wrong because the games start but I don't notice anything. Do you have to activate it somewhere in Steam VR? I have tried to leave the parameters as they come in the openvr_mod.cfg file and also changing the values, but then how do I activate them in the game?
By the way, in the games I have tried, if I try to try the new version V1.1, the games do not start, but with the previous version they do.
 Thanks

**Comment by fholger** [comment]
As per the other thread, I assume this issue is solved.
