### ISSUE TITLE
Changing settings at runtime?

### ISSUE THREAD

**Issue by Raicuparta** [fholger/openvr_fsr#60]
Would it be possible to make it automatically reload the settings if the file is changed, and applying the changes at runtime?

Alternatively, maybe some way of programmatically changing settings via some API?

**Comment by fholger** [comment]
Not really. The main issue is that I can't force games to re-evaluate their render resolution, so I can't definitively change the render scale setting after startup. A few games will ask OpenVR for the current render resolution every frame and update their render targets if necessary, but many don't, and there is nothing to be done about it.

**Comment by Raicuparta** [comment]
Makes sense. I want to add in-game fsr options to my VR mods (outer wilds and firewatch). I'll just make it edit the config file and ask the user to restart the game to apply the settings, not a big deal. Thanks!
