### ISSUE TITLE
User interface

### ISSUE THREAD

**Issue by liam0n** [fholger/openvr_fsr#62]
Is it possible to add an user interface like in OpenComposite? This would enhance the usability for daily use a lot.
Especially for switching and managing profiles in a huge steam library.

P.S. Probably it works with any openvr game outside the steam games folder too?

EDIT, add link
https://gitlab.com/znixian/OpenOVR/blob/master/README.md#system-wide-installation

**Comment by fholger** [comment]
Anything's possible, but I have neither the time nor the desire to do UI development. So this is only going to happen if someone else will pick it up.

It looks like someone already did start such a project: https://github.com/tappi287/openvr_fsr_app
To be clear, I didn't test it nor do I know if it actually works.

**Comment by Hydr4bytes** [comment]
I made this tool for installing openvr_fsr system-wide, so far it has worked great for me:
https://boneworks.thunderstore.io/package/L4rs/QuickFSR/

**Comment by fholger** [comment]
Since there are decent third-party UIs available and I do not want to spend time on it, myself, I'm going to close this issue.
