### ISSUE TITLE
Using FSR with opencomposite

### ISSUE THREAD

**Issue by Rencio7** [fholger/openvr_fsr#63]
FSR Works well with SkyrimVR and I appreciate it  but I don't use it because I like the performance increase etc when using opencomposite https://gitlab.com/znixian/OpenOVR. I tried replacing the dll with opencomposite but it doesn't work. Can  this be easily fixed? Thanks for your time. L

**Comment by fholger** [comment]
I've had reports that it works if you install OpenComposite globally. However, for the per-game installation, both mods need to replace the same DLL, so they just can't work together at the moment.
