### ISSUE TITLE
Assetto Corsa Competitione is not working correctly

### ISSUE THREAD

**Issue by CarstenMK** [fholger/openvr_fsr#66]
Hi,
I just tried the v1.0 with ACC. Game is starting but has missing textures in the car (steering wheel, suit, gloves, buttons etc.). Anyone with an idea what the problem could be? You can see the diff between with and without the MOD.

![20210811102302_1](https://user-images.githubusercontent.com/88770215/128999013-ea415e92-921c-4dc8-8e4e-54fe74c08a94.jpg)
![20210811103319_1](https://user-images.githubusercontent.com/88770215/128999030-6f961f5a-75f8-435f-968d-d1d99a287ffe.jpg)

**Comment by fholger** [comment]
Try disabling `applyMipBias` in the config file.

**Comment by CarstenMK** [comment]
That works! Thanks for help
