### ISSUE TITLE
Don't know if FSR is on or not.

### ISSUE THREAD

**Issue by MexxPex** [fholger/openvr_fsr#67]
I have no idea if FSR is working or not after I've installed it.

**Comment by fholger** [comment]
First check is, does it create an `openvr_mod.log` file next to the DLL when you run the game? If not, it is definitely not active. If the log is there, the next thing you can do is to set `debugMode` to `true` in the config file. In game, you should then see kind of a highlighted circle in the center of your view. If you are seeing that, the mod is active and working.

**Comment by Adil3tr** [comment]
I had a similar question, does the radius value still apply when your render scale is great than 1? Like is it using FSR across the entire image or only within the radius and bilinear on the rest (and can I turn that part off)?

**Comment by fholger** [comment]
Only within the radius. If you want the entire image affected, just set the radius to a high value like 2.
