### ISSUE TITLE
Error when submitting for eye 0/1: 108 Assetto Corsa Competizione

### ISSUE THREAD

**Issue by AndrewJungle** [fholger/openvr_fsr#68]
[openvr_mod.log](https://github.com/fholger/openvr_fsr/files/6978298/openvr_mod.log)
Hey, I recently installed this for ACC and it is working, but it is constantly spamming the log file with this error.

Thanks.

**Comment by DigitalFriends** [comment]
I got the same error, not sure what it means. 

`Initializing hooks...
Requested interface IVRSystem_019
Injecting GetRecommendedRenderTargetSize into IVRSystem_019
Requested interface IVRSystem_019
Requested interface IVRCompositor_022
Injecting Submit into IVRCompositor_022
Requested interface IVROverlay_018
Requested interface IVRChaperone_003
Requested interface IVRExtendedDisplay_001
Error when submitting for eye 0: 101
Error when submitting for eye 1: 101
Error when submitting for eye 0: 101
Error when submitting for eye 1: 101
Error when submitting for eye 0: 101
Error when submitting for eye 1: 101
Error when submitting for eye 0: 101
Error when submitting for eye 1: 101`

Also got this
`Creating replacement sampler for 00000249AF884180 with MIP LOD bias -0.376783
Creating replacement sampler for 00000249AF884E00 with MIP LOD bias -0.376783
Creating replacement sampler for 00000249AF883B40 with MIP LOD bias -0.376783
Creating replacement sampler for 0000024B22F92980 with MIP LOD bias -0.376783
Creating replacement sampler for 0000024BDEAC1C40 with MIP LOD bias -0.376783
Creating replacement sampler for 00000249AF883500 with MIP LOD bias -0.376783`

And some more

`Error when submitting for eye 1: 101
Creating post-processing resources
Input texture is in SRGB color space
Requested interface IVRSystem_022
Projection center for eye 0: 0.51701, 0.571904
Requested interface IVRSystem_022
Projection center for eye 1: 0.48256, 0.57124
Creating upscaled texture of size 4838x2685
Requested interface IVRSystem_022
Projection center for eye 0: 0.51701, 0.571904
Requested interface IVRSystem_022
Projection center for eye 1: 0.48256, 0.57124
Creating sharpened texture of size 4838x2685
Injecting PSSetSamplers into D3D11DeviceContext
Creating replacement sampler for 00000249AF884680 with MIP LOD bias -0.376783
Creating replacement sampler for 00000249AF885300 with MIP LOD bias -0.376783
Creating replacement sampler for 00000249AF883DC0 with MIP LOD bias -0.376783
Creating replacement sampler for 00000249AF884900 with MIP LOD bias -0.376783
Creating replacement sampler for 00000249AF884040 with MIP LOD bias -0.376783
Creating replacement sampler for 0000000000000000 with MIP LOD bias -0.376783
Creating shader resource view for input texture 0000024B231EE198
Texture has size 3726x2068 and format 90
Error when submitting for eye 0: 101
Error when submitting for eye 1: 101
Creating replacement sampler for 0000024B232DF480 with MIP LOD bias -0.376783
Creating replacement sampler for 00000249AF883640 with MIP LOD bias -0.376783
Creating replacement sampler for 0000024A9CA990C0 with MIP LOD bias -0.376783
Creating replacement sampler for 00000249AF883C80 with MIP LOD bias -0.376783
Error when submitting for eye 0: 108`

**Comment by fholger** [comment]
The errors should be harmless. 101 means that the compositor was out of focus - I'm not sure under what conditions this error occurs, but it is not something you need to worry about and it is not caused by this mod. The mod just catches and reports the errors. 108 means that the game submitted a render image for one of the eyes that was already submitted in this frame. This is most likely a mistake in the game itself and is again merely reported by the mod.

**Comment by DigitalFriends** [comment]
> 
> 
> The errors should be harmless. 101 means that the compositor was out of focus - I'm not sure under what conditions this error occurs, but it is not something you need to worry about and it is not caused by this mod. The mod just catches and reports the errors. 108 means that the game submitted a render image for one of the eyes that was already submitted in this frame. This is most likely a mistake in the game itself and is again merely reported by the mod.

Cool, thanks for the explanation!
