### ISSUE TITLE
Possibility to decrease/lower the "out of radius" quality rendering ?

### ISSUE THREAD

**Issue by DouglasteR** [fholger/openvr_fsr#69]
As the tittle says, this plugin is amazing and have great potential.

Using the FSR "only" lowers the mipmap (as i believe) outside the defined center area. 

It is possible to implement a resolution decrease too ? This way we can get really great performance for older/not compatible games.

Thanks and keep up the good work !

**Comment by fholger** [comment]
You are talking about fixed foveated rendering? No, that is not possible. There is no generic way to implement and inject that into D3D11 games. For DX12 or Vulkan, it could theoretically be done with variable rate shading, but that would only work with RTX or RDNA2 cards.

**Comment by DouglasteR** [comment]
> You are talking about fixed foveated rendering? No, that is not possible. There is no generic way to implement and inject that into D3D11 games. For DX12 or Vulkan, it could theoretically be done with variable rate shading, but that would only work with RTX or RDNA2 cards.

Yes, FVR.

Sad, so it would be hardware dependent :(

**Comment by fholger** [comment]
That, and there are very few VR games based on DX12 or Vulkan, anyway.
