### ISSUE TITLE
Make it possible to control FSR independently for each eye

### ISSUE THREAD

**Issue by eemanuelsson** [fholger/openvr_fsr#70]
I am interested in being able to control the FSR settings for each eye independently.  The main reason for this is that my eye sight is pretty bad on one eye and I think I can get away with rendering that eye in a much lower resolution than my "good eye".

If this was possible I could turn this physical problem into kind of an advantage and shift performance to my good eye where it would be put to better use.

**Comment by fholger** [comment]
That is unfortunately not really possible. I cannot tell the game to render at different resolutions for each eye, that is something that the games would have to implement themselves. Best I could do is use different radii of FSR applications for each eye, but the savings would be fairly small for quite a bit of effort I'd have to put into this.
