### ISSUE TITLE
thank you very much!

### ISSUE THREAD

**Issue by JBB888** [fholger/openvr_fsr#71]
I Have no issue, just wanted to thank  u for your incredible work! I think everyone here owes you a beer at least! great work my friend! give us an adress to contribute funds to you I'm sure we all will show our appreciation :)

**Comment by MiguelCatalan** [comment]
@fholger consider putting a https://www.buymeacoffee.com/ kind of thing. Probably a lot of us will buy you more than a beer.

**Comment by fholger** [comment]
Thanks, and it's great to hear it has some value :)

However, monetary contributions aren't necessary. I'm financially secure, and this is just a fun side project for me. I prefer not to take money for it, as that always brings extra responsibilities that I do not want to deal with. The thought is appreciated, though :)
