### ISSUE TITLE
The "sweet spot" is not really in the center of the frame

### ISSUE THREAD

**Issue by jacklul** [fholger/openvr_fsr#73]
It seems that the whole sweet spot is offset a bit too much to the bottom of the frame rather than being it in the middle.

https://i.imgur.com/sdS9us9.jpg (I can clearly see half of the top red part in the headset, the line that divides upscaled and non-upscaled parts of the images are a bit distracting)
https://imgur.com/uqiEKAW
[Log](https://pastebin.com/qcSAypzr)

The screenshot and video were taken directly from the Quest 1 recording feature because the debug overlay does not show up on the NVIDIA Shadowplay recording.
Tested in Phasmophobia, happens in VRChat as well (both Unity).

Would it be possible to add a parameter to the config that could move the area?

**Comment by fholger** [comment]
Far as I can tell, the behaviour is correct. The Quest reports that its projection center is offset in the vertical direction, and therefore the sweet spot must also be offset. If you find the blend at the border of the two image parts distracting (even when debugMode is off), you may wish to increase the radius a bit to push that line further out.

**Comment by jacklul** [comment]
Now I'm wondering why even this is a thing for the Quest, this kinda explains why SteamVR screenshots have way more stuff rendered at the bottom of the image than the headset can even display...

It would probably be more beneficial to let the user move the sweet spot, especially that I've noticed the center radius is sometimes different between various games...

Possibly related to #27 ?

**Comment by jacklul** [comment]
Implemented this in my fork - https://github.com/jacklul/openvr_fsr/tree/offsets
No idea if this is the proper solution but it works

**Comment by jacklul** [comment]
The update doesn't really make any difference for me, updated my fork for anyone who is having same problem though
