### ISSUE TITLE
Issues i found with blade and sorcery 

### ISSUE THREAD

**Issue by XxsjrapsxX** [fholger/openvr_fsr#74]
First of i notice that in game looking at the book its capped at 60 fps, meanwhile the normal steam driver allows me up to at minimum of 90 for a cap and a max of 120, also any attempts to up the texture detail after the mod is installed causes a crash. Also while in game sometimes if you move a weird way, it just crashes the game, and causes all other applications open at the time to be basically unresponsive. Blade and sorcery may work but unless it gets a game specific optimization, i would not recommend using this for it!

**Comment by fholger** [comment]
I tested it, and I had no issues whatsoever. Can you attach the openvr_mod.log, and also what kind of headset and hardware are you running?

**Comment by XxsjrapsxX** [comment]
i run a quest 2 via virtual desktop, i got the fps part from the book where it says it runs at 60 fps for some reason. 
[openvr_mod.log](https://github.com/fholger/openvr_fsr/files/6995889/openvr_mod.log)
though i tried it again, no crash but still locked at 60 fps

**Comment by XxsjrapsxX** [comment]
still have yet to find out why its locked at 60 fps, is this some weird bug no one else has, i really want to fix it if so

**Comment by arrudaj97** [comment]
Try turning off SSW in the streaming settings on virtual desktop
