### ISSUE TITLE
does not work with rec room

### ISSUE THREAD

**Issue by Spherey** [fholger/openvr_fsr#75]
apparently when launching it with rec room an error appears saying "invalid file version" due to rec room using easy anti cheat

**Comment by fholger** [comment]
If it's blocked by an anti-cheat measure, there isn't really anything I can do. Does Rec Room even suffer from high GPU load, though?

**Comment by SushiRoll55** [comment]
Indeed it does. Man I wish it worked with Rec Room since lag is very common for me in that game specifically.

**Comment by fholger** [comment]
Unfortunately, there isn't really anything I can do about anti-cheat systems, so I don't think this is fixable.
