### ISSUE TITLE
Boneworks won’t open

### ISSUE THREAD

**Issue by SocksnSandles** [fholger/openvr_fsr#78]
It works perfectly with the included dll, but the far one causes boneworks to fail to boot. I’ve tried reinstalling boneworks to no avail. Or there games work for me and boneworks seems to work for others.

**Comment by fholger** [comment]
Is there any error message, is there a `openvr_mod.log` after trying to launch the game?

All I can say is that Boneworks definitely works. I'm assuming you put the DLL into Boneworks\Boneworks_Data\Plugins?
