### ISSUE TITLE
Skyrim VR and Open Composite Runtime Switcher Error

### ISSUE THREAD

**Issue by avolpe95** [fholger/openvr_fsr#80]
Unknown render model name: €QXPerLeftHand

Getting this error when i try to start the game with the fsr mod installed and open composite runtime switcher set to open composite.  the window appears black and the error shows up and when I hit ok it crashes. 
been trying to run the fsr mod with open composite together. it works when the normal openvr_api.dll is in the skyrimvr folder Open composite will run when the switcher is on open composite and steam vr will run when the switch is on steam vr but when i replace the openvr_api.dll with the one for fsr and set the switch to open composite then i get this error and i cant run the game

**Comment by fholger** [comment]
Does it work with any other game?
