### ISSUE TITLE
Fallout 4 Index Controller Fix with FSR?

### ISSUE THREAD

**Issue by IronOutsider** [fholger/openvr_fsr#81]
Would it be possible to get a version of the openvr_api.dll with the "index controller" hack that makes the index controllers show up as oculus controls bundled with the FSR enhancements? Currently, the only way to get playable controls in Fallout 4 is with your Fov4Index Controller Hack v1.1. Would be awesome to have playable index control + improved performance.

**Comment by wenhaosun** [comment]
Amazing, I was literally going to write this exact same comment. Only 33 minutes apart, haha.

**Comment by fholger** [comment]
That fix hasn't been necessary for a while. All you need is the adjusted controller bindings with the controllers set to emulate Touch. You also need to have SteamVR started and the controllers turned on before you launch the game. But as long as you do that, the game works fine with Index controllers without the fix.

**Comment by IronOutsider** [comment]
OMG your right... There's a wabbajack modpack called "Fallout VR Essentials" that is still using your previous controller hacked version of openvr_api.dll.  I was using Fallout VR Essential Bindings from the Steam VR shared bindings (most downloaded and popular one by the way). If you edit the binding and go to Set Up Legacy Actions -> Click Oculus Touch and save as a personal binding, then it works. Thanks man! I'll call this closed.
