### ISSUE TITLE
Can you get banned for using this online?

### ISSUE THREAD

**Issue by Motorak** [fholger/openvr_fsr#82]
I know this is not a issue, but I have no idea if it´s safe to use online in games like Pavlov VR or Project Cars 2 (which btw works, PC2 uses old open vr version same one as the ACC (which someone made a mod for that works with PC2 too).

This mod is modifying the actual dll. file, so could this get me banned?

**Comment by jacklul** [comment]
Pretty standard rule: In games protected by anti cheat systems you're applying the modification at your own risk.
_As far as I know Pavlov does not use any anti-cheat system currently._

**Comment by fholger** [comment]
Possibly. You'd have to ask the developers of those games. The FSR mod itself is certainly not a cheat, but the ability to modify any game DLL opens the door wide for cheating, so it's very possible or even likely that anti-cheat systems will flag any modified DLLs.
