### ISSUE TITLE
Boneworks did upscale, but there was no change in performance

### ISSUE THREAD

**Issue by ThatKrazyGoat** [fholger/openvr_fsr#83]
In game I have no change in FPS

**Comment by fholger** [comment]
That doesn't mean it's not working. Please post the openvr_mod.log.

**Comment by ThatKrazyGoat** [comment]
Initializing hooks...
Requested interface IVRSystem_019
Injecting GetRecommendedRenderTargetSize into IVRSystem_019
Shutting down hooks...
Initializing hooks...
Requested interface IVRSystem_019
Injecting GetRecommendedRenderTargetSize into IVRSystem_019
Requested interface IVRChaperone_003
Requested interface IVRChaperoneSetup_005
Requested interface IVRCompositor_022
Injecting Submit into IVRCompositor_022
Requested interface IVROverlay_018
Requested interface IVRCompositor_022
Requested interface IVROverlay_019
Requested interface IVRInput_006
Requested interface IVRInput_006
Requested interface FnTable:IVRInput_006
Requested interface IVRCompositor_022
Requested interface FnTable:IVRCompositor_022
Requested interface IVRSystem_019
Requested interface FnTable:IVRSystem_019
Requested interface IVROverlay_019
Requested interface FnTable:IVROverlay_019
Requested interface IVRScreenshots_001
Requested interface FnTable:IVRScreenshots_001
Creating post-processing resources
Input texture is in SRGB color space
Creating upscaled texture of size 1824x1840
Creating sharpened texture of size 1824x1840
Injecting PSSetSamplers into D3D11DeviceContext
Creating replacement sampler for 000001A5C1329E20 with MIP LOD bias -1
Creating replacement sampler for 000001A67DF98AA0 with MIP LOD bias -1
Creating replacement sampler for 000001A67DF982E0 with MIP LOD bias -1
Creating replacement sampler for 000001A67DF98CE0 with MIP LOD bias -1
Creating replacement sampler for 000001A67DF98520 with MIP LOD bias -1
Creating replacement sampler for 0000000000000000 with MIP LOD bias -1
Creating shader resource view for input texture 000001A58E48BF78
Texture has size 912x920 and format 27
Creating shader resource view for input texture 000001A58E48C1F8
Texture has size 912x920 and format 27
Creating replacement sampler for 000001A67DF99160 with MIP LOD bias -1
Creating replacement sampler for 000001A689BE6AA0 with MIP LOD bias -1
Creating replacement sampler for 000001A5F6A15D60 with MIP LOD bias -1
Creating replacement sampler for 000001A5C0B18FA0 with MIP LOD bias -1
Creating replacement sampler for 000001A5C0B16620 with MIP LOD bias -1
Creating replacement sampler for 000001A5C0B17A60 with MIP LOD bias -1
Creating replacement sampler for 000001A5C1465C60 with MIP LOD bias -1
Creating replacement sampler for 000001A5C14671A0 with MIP LOD bias -1
Creating replacement sampler for 000001A5C0938F60 with MIP LOD bias -1
Creating replacement sampler for 000001A61C05FCA0 with MIP LOD bias -1
Creating replacement sampler for 000001A61C05F4A0 with MIP LOD bias -1
Requested interface IVRCompositor_013
Requested interface FnTable:IVRCompositor_013
Creating replacement sampler for 000001A628822E20 with MIP LOD bias -1
Error when submitting for eye 0: 108
Error when submitting for eye 1: 108
Creating replacement sampler for 000001A6296B3CE0 with MIP LOD bias -1
Error when submitting for eye 0: 108
Error when submitting for eye 1: 108
Texture size changed, recreating resources...
Creating post-processing resources
Input texture is in SRGB color space
Creating upscaled texture of size 912x920
Creating sharpened texture of size 912x920
Creating replacement sampler for 000001A5C1329D20 with MIP LOD bias -1
Creating replacement sampler for 000001A5C1327B60 with MIP LOD bias -1
Creating replacement sampler for 000001A689BE6960 with MIP LOD bias -1
Creating replacement sampler for 000001A5C1329660 with MIP LOD bias -1
Creating replacement sampler for 000001A5C132A860 with MIP LOD bias -1
Creating shader resource view for input texture 000001A688F3F038
Texture has size 456x460 and format 27
Creating shader resource view for input texture 000001A688F3E2F8
Texture has size 456x460 and format 27
Creating replacement sampler for 0000000000000000 with MIP LOD bias -1
Creating replacement sampler for 000001A5C1465C60 with MIP LOD bias -1
Creating replacement sampler for 000001A67DF98AA0 with MIP LOD bias -1
Creating replacement sampler for 000001A5F6A15D60 with MIP LOD bias -1
Creating replacement sampler for 000001A67DF982E0 with MIP LOD bias -1
Creating replacement sampler for 000001A67DF98520 with MIP LOD bias -1
Creating replacement sampler for 000001A689BE6AA0 with MIP LOD bias -1
Creating replacement sampler for 000001A67DF99160 with MIP LOD bias -1
Creating replacement sampler for 000001A5C14671A0 with MIP LOD bias -1
Creating replacement sampler for 000001A5C1329E20 with MIP LOD bias -1
Creating replacement sampler for 000001A67DF98CE0 with MIP LOD bias -1
Creating replacement sampler for 000001A5C0B18FA0 with MIP LOD bias -1
Creating replacement sampler for 000001A5C0B16620 with MIP LOD bias -1
Creating replacement sampler for 000001A5C0B17A60 with MIP LOD bias -1
Texture size changed, recreating resources...
Creating post-processing resources
Input texture is in SRGB color space
Creating upscaled texture of size 456x460
Creating sharpened texture of size 456x460
Creating replacement sampler for 000001A5C1329D20 with MIP LOD bias -1
Creating replacement sampler for 000001A5C1327B60 with MIP LOD bias -1
Creating replacement sampler for 000001A689BE6960 with MIP LOD bias -1
Creating replacement sampler for 000001A5C1329660 with MIP LOD bias -1
Creating replacement sampler for 000001A6299445E0 with MIP LOD bias -1
Creating shader resource view for input texture 000001A688F470B8
Texture has size 228x230 and format 27
Creating shader resource view for input texture 000001A688F47378
Texture has size 228x230 and format 27
Creating replacement sampler for 0000000000000000 with MIP LOD bias -1
Creating replacement sampler for 000001A5C1465C60 with MIP LOD bias -1
Creating replacement sampler for 000001A67DF98AA0 with MIP LOD bias -1
Creating replacement sampler for 000001A5F6A15D60 with MIP LOD bias -1
Creating replacement sampler for 000001A67DF982E0 with MIP LOD bias -1
Creating replacement sampler for 000001A67DF98520 with MIP LOD bias -1
Creating replacement sampler for 000001A689BE6AA0 with MIP LOD bias -1
Creating replacement sampler for 000001A67DF99160 with MIP LOD bias -1
Creating replacement sampler for 000001A5C14671A0 with MIP LOD bias -1
Creating replacement sampler for 000001A5C1329E20 with MIP LOD bias -1
Creating replacement sampler for 000001A67DF98CE0 with MIP LOD bias -1
Creating replacement sampler for 000001A5C0B18FA0 with MIP LOD bias -1
Creating replacement sampler for 000001A5C0B16620 with MIP LOD bias -1
Creating replacement sampler for 000001A5C0B17A60 with MIP LOD bias -1
Texture size changed, recreating resources...
Creating post-processing resources
Input texture is in SRGB color space
Creating upscaled texture of size 912x920
Creating sharpened texture of size 912x920
Creating replacement sampler for 000001A5C1329D20 with MIP LOD bias -1
Creating replacement sampler for 000001A5C1327B60 with MIP LOD bias -1
Creating replacement sampler for 000001A689BE6960 with MIP LOD bias -1
Creating replacement sampler for 000001A5C1329660 with MIP LOD bias -1
Creating replacement sampler for 000001A629945260 with MIP LOD bias -1
Creating shader resource view for input texture 000001A688F3E2F8
Texture has size 456x460 and format 27
Creating shader resource view for input texture 000001A688F3F038
Texture has size 456x460 and format 27
Creating replacement sampler for 0000000000000000 with MIP LOD bias -1
Creating replacement sampler for 000001A5C1465C60 with MIP LOD bias -1
Creating replacement sampler for 000001A67DF98AA0 with MIP LOD bias -1
Creating replacement sampler for 000001A5F6A15D60 with MIP LOD bias -1
Creating replacement sampler for 000001A67DF982E0 with MIP LOD bias -1
Creating replacement sampler for 000001A67DF98520 with MIP LOD bias -1
Creating replacement sampler for 000001A689BE6AA0 with MIP LOD bias -1
Creating replacement sampler for 000001A67DF99160 with MIP LOD bias -1
Creating replacement sampler for 000001A5C14671A0 with MIP LOD bias -1
Creating replacement sampler for 000001A5C1329E20 with MIP LOD bias -1
Creating replacement sampler for 000001A67DF98CE0 with MIP LOD bias -1
Creating replacement sampler for 000001A5C0B18FA0 with MIP LOD bias -1
Creating replacement sampler for 000001A5C0B16620 with MIP LOD bias -1
Creating replacement sampler for 000001A5C0B17A60 with MIP LOD bias -1
Texture size changed, recreating resources...
Creating post-processing resources
Input texture is in SRGB color space
Creating upscaled texture of size 1824x1840
Creating sharpened texture of size 1824x1840
Creating replacement sampler for 000001A5C1329D20 with MIP LOD bias -1
Creating replacement sampler for 000001A5C1327B60 with MIP LOD bias -1
Creating replacement sampler for 000001A689BE6960 with MIP LOD bias -1
Creating replacement sampler for 000001A5C1329660 with MIP LOD bias -1
Creating replacement sampler for 000001A5C1329760 with MIP LOD bias -1
Creating replacement sampler for 000001A6299455A0 with MIP LOD bias -1
Creating shader resource view for input texture 000001A688F470B8
Texture has size 912x920 and format 27
Creating shader resource view for input texture 000001A688F47B38
Texture has size 912x920 and format 27
Creating replacement sampler for 0000000000000000 with MIP LOD bias -1
Creating replacement sampler for 000001A5C1465C60 with MIP LOD bias -1
Creating replacement sampler for 000001A67DF98AA0 with MIP LOD bias -1
Creating replacement sampler for 000001A5F6A15D60 with MIP LOD bias -1
Creating replacement sampler for 000001A67DF982E0 with MIP LOD bias -1
Creating replacement sampler for 000001A67DF98520 with MIP LOD bias -1
Creating replacement sampler for 000001A689BE6AA0 with MIP LOD bias -1
Creating replacement sampler for 000001A67DF99160 with MIP LOD bias -1
Creating replacement sampler for 000001A5C14671A0 with MIP LOD bias -1
Creating replacement sampler for 000001A5C1329E20 with MIP LOD bias -1
Creating replacement sampler for 000001A67DF98CE0 with MIP LOD bias -1
Creating replacement sampler for 000001A5C0B18FA0 with MIP LOD bias -1
Creating replacement sampler for 000001A5C0B16620 with MIP LOD bias -1
Creating replacement sampler for 000001A5C0B17A60 with MIP LOD bias -1
Creating replacement sampler for 000001A628822E20 with MIP LOD bias -1

this is what the log says, so it did upscale, but there was no change in fps. I am currently using a GeForce GTX 1650 ti and a 10th gen i5 processor.

**Comment by fholger** [comment]
How are you measuring fps, and what are your fps? 

Your resolutions are ridiculously low, so I'd wager that you are either already hitting the maximum FPS for your headset, or you are not bottlenecked by the graphics.

**Comment by ThatKrazyGoat** [comment]
I am using the fpsvr app from steam, and I am still getting 38-46 average FPS.

**Comment by fholger** [comment]
What are the reported frame times for CPU and GPU?

**Comment by ThatKrazyGoat** [comment]
With or without the mod?

**Comment by fholger** [comment]
Both.

**Comment by fholger** [comment]
Any updates on this?

**Comment by krillme** [comment]
Boneworks is extremely CPU heavy due to its dozens upon dozens of simultaneous complex physics calculations and FSR only improves performance on the GPU side.
