### ISSUE TITLE
In ReshadeVR, FPS drops out when video is being played in VRChat.

### ISSUE THREAD

**Issue by ni1chigo2115** [fholger/openvr_fsr#84]
https://github.com/fholger/reshade

I know it's not very good, but I couldn't raise the issue on ReshadeVR, so I'm posting it here.
When using ReshadeVR, if you move to an instance where a video is playing, the FPS drops significantly and becomes unplayable.
Reshade has powerful SMAA and other features that allow you to get better AA results than using the driver's built-in FXAA.

Translated with www.DeepL.com/Translator (free version)

**Comment by fholger** [comment]
You can try a newer Reshade build someone else is maintaining over here: https://vrtoolkit.retrolux.de/
Other than that, I'm afraid I can't really help you.
