### ISSUE TITLE
Not really an issue but a warning to fellow DCS gamers

### ISSUE THREAD

**Issue by davidp57** [fholger/openvr_fsr#85]
First, thanks for this, it's awesome !

I'm playing [DCS World](https://www.digitalcombatsimulator.com/), a military flight sim.
There is a small caveat when using your driver/mod, in that it is only used by the game when started in SteamVR.
Users of Oculus headsets will not see any enhancement because the driver/mod is simply not used.
The solution is to start the game with the `--force_steam_VR` option.

Doing this, I have gained 30% of my frametime !

**Comment by fholger** [comment]
You could perhaps add this to the [wiki](https://github.com/fholger/openvr_fsr/wiki) entry for DCS.

**Comment by davidp57** [comment]
Way ahead of you ;)
I did it right away ^^
