### ISSUE TITLE
Does this work with/replace CAS?

### ISSUE THREAD

**Issue by Adil3tr** [fholger/openvr_fsr#86]
I tried playing Pavlov with your CAS reshade enabled and this FSR patch. It was very oversharpened and I could see the radius clearly and it wasn't stereo-correct. I assume that part has been fixed but I was wondering if this FSR mod still retains the color and contrast benefits of CAS, making CAS unnecessary, or if I should use them together with the sharpening turned off of this and the radius set to 2?

**Comment by fholger** [comment]
FSR includes its own CAS sharpener variant, so adding CAS on top is unnecessary und not recommended.

**Comment by Adil3tr** [comment]
I know it has sharpening, but what about the color and contrast adjustment? That's a big improvement when using the index.

**Comment by fholger** [comment]
It does not have those, but neither does CAS. I added some to my Reshade preset, but they are not technically part of CAS. You can continue using a color correcting Reshade preset if you like, but it should not do sharpening.

**Comment by polyjitter** [comment]
Reshade does not seem to activate while using FSR. Is this a known issue?

**Comment by Adil3tr** [comment]
> 
> 
> It does not have those, but neither does CAS. I added some to my Reshade preset, but they are not technically part of CAS. You can continue using a color correcting Reshade preset if you like, but it should not do sharpening.

Is there a guide to making a reshade present that works with OpenVR without the sharpening?
