### ISSUE TITLE
Dx10 

### ISSUE THREAD

**Issue by Davizmg** [fholger/openvr_fsr#87]
first of all, thanks for your work,could you make it compatible with dx10?  in this way it would work in raceroom,raceroom in vr uses dx10, not dx9.. retrolux has made its version of reshade compatible with dx10 and it works perfectly

**Comment by fholger** [comment]
That's not possible. OpenVR *does not* support DX9 or DX10, so I cannot add support for it, either. It doesn't matter if Raceroom internally renders with DX10, it has to submit DX11 textures to OpenVR, because there is no other option.
