### ISSUE TITLE
Skyrim VR not able to save if fx is active (ingame perforemance and looks are grate)

### ISSUE THREAD

**Issue by Sever111222** [fholger/openvr_fsr#88]
In game quick save and save functions are greyed out, while fx is enabled

**Comment by Sever111222** [comment]
So, it seems, when you set "applyMIPBias": false, saves work again. No issues there anymore.

**Comment by fholger** [comment]
That... makes no sense to me, and I've not observed that, either. I guess it could be a conflict with another mod hooking into DX11 functions, but it sounds very strange.

**Comment by Sever111222** [comment]
Maybe something was wrong with my system, and started working again, when I was changing this setting, and it is just coincidence.. Anyway, thanks for the mode made available, SkyrimVR looks and performs, with g2 and rtx 2070, wonderful! I can play with 100% resolution in SteamVR and in game, applying openvr fsr at highest setting and it runs at 90hz. No other mods installed.
