### ISSUE TITLE
Seems to work with Myst

### ISSUE THREAD

**Issue by Memnarch** [fholger/openvr_fsr#89]
Heyho, just wanted to give feedback. Tried it out with the new Myst in SteamVR on my Reverb G2 and it seems to work fine :)

**Comment by fholger** [comment]
Best to report it in the [Wiki](https://github.com/fholger/openvr_fsr/wiki) :)

**Comment by Memnarch** [comment]
OH didn't see you allow public changes. Done :)
Any tip for creating comparision images? Have a Mixed Reality Headset (HP Reverb G2)

**Comment by fholger** [comment]
Unfortunately, there is no easy way to extract meaningful comparison shots. You can try the SteamVR mirror view, but that shows scaled down images, so the effect may not be super visible in them.
