### ISSUE TITLE
Making it work with Star Wars Squadrons

### ISSUE THREAD

**Issue by koelscha** [fholger/openvr_fsr#94]
I have verified that Easy Anti Cheat blocks use of openvr fsr mod – the game won't start. (I run it with PiTool and Steam VR.)
However, Anti Cheat can be disabled with a simple renaming, as is described here:
https://www.pcgamingwiki.com/wiki/Star_Wars:_Squadrons
With this modification, the mod works and gives a significant FPS increase. I had to turn sharpening off in the in-game video settings for best visual results.
I only play Squadrons offline, so the Anti Cheat is not an issue for me, but given the multiplayer focus of the game it may well be for others, so please take that into consideration if you try this workaround.
Many thanks to Holger for this outstanding contribution!

**Comment by fholger** [comment]
Good to know. You may want to add that information to the Wiki :)

**Comment by koelscha** [comment]
Done!

**Comment by fholger** [comment]
Excellent, thank you! :)
I'll close this one, then.

**Comment by ASchneiderBR** [comment]
Hello! Squadrons just got a 4gb update, maybe FSR works now? I'll give it a try with this Anti Cheat "hack" :) thanks!
