### ISSUE TITLE
SteamVR Dashboard

### ISSUE THREAD

**Issue by polyjitter** [fholger/openvr_fsr#95]
Looking for a way to apply this to the steamvr dashboard, so I can turn down the render resolution for cross-all-game performance while still maintaining dashboard clarity. Is this currently feasible?

**Comment by fholger** [comment]
I'm not sure I understand what your goal here is? The dashboard is basically just a fancy 2D plane. It is not rendering intensive and would not benefit from FSR, and besides, it's only rendered when you open it on purpose, anyway.

**Comment by fholger** [comment]
Feel free to reopen with more info, but for now I'm assuming there isn't really anything to be done here.
