### ISSUE TITLE
Fallout 4 vr - error in log

### ISSUE THREAD

**Issue by BrziJoe** [fholger/openvr_fsr#96]
Hello Fholger. I was playing lately Fo4VR with fsr, of course. I was sure it is working as it looks incredible good, and then I saw strange errors in log. I tried debug mode, and I saw circles, but errors are still in log.
Can you please check what is happening.
PS: I play DLC Far Harbor, with only one mod against missing/wrong textures in original DLC (VR Optimization Project - Far Harbor DLC-28850-1-150). Sometimes I see one light layer of one frozen screen, but this is only in some situations, and short. It does not bother me while playing.

[openvr_mod - Kopie 2.0 with debug.log](https://github.com/fholger/openvr_fsr/files/7141962/openvr_mod.-.Kopie.2.0.with.debug.log)
[openvr_mod - Kopie 2.0.log](https://github.com/fholger/openvr_fsr/files/7141963/openvr_mod.-.Kopie.2.0.log)
[openvr_mod - Kopie 1.0.log](https://github.com/fholger/openvr_fsr/files/7141964/openvr_mod.-.Kopie.1.0.log)
[openvr_mod - Kopie 1.4.log](https://github.com/fholger/openvr_fsr/files/7141965/openvr_mod.-.Kopie.1.4.log)

**Comment by fholger** [comment]
Are you referring to the "Error when submitting for eye X: 101"? These are completely normal, they are not even caused by the mod, just reported by it. They'd only be a problem if they kept being repeated over and over in the log.

**Comment by BrziJoe** [comment]
Yes, that. Thank you.
The FSR is working excellent with Fo4vr, really nice 👍

**Comment by fholger** [comment]
Good to hear :)
