### ISSUE TITLE
Compatibility with reshade

### ISSUE THREAD

**Issue by Agahnim90** [fholger/openvr_fsr#98]
Hi ! 

Firstly, thanks a lot for your work, such a great feature, huge addition for the VR community in my opinion.

But i would have a question regarding the compatibility with the reshade feature, i mean this one particularly : https://github.com/crosire/reshade . To be used along with https://vrtoolkit.retrolux.de/.

Is there any compatibility issue to expect when use it with openvr_fsr ? Would it be useful by the way (as openvr_fsr already have a sharpening option) ?

Regards,
A90

**Comment by fholger** [comment]
Yes, FSR has its own sharpening built-in, and I'd generally caution against layering sharpening effects. But you'll have to try for yourself. There is no inherent incompatibility between the two, but there's no guarantee, either, that it'll work with any particular game.

**Comment by Agahnim90** [comment]
Alright, will try then, to figure out which one works the best. 

Thanks a lot!
